# Generated by Django 4.2.7 on 2023-11-24 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название направления')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'направления',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('branch', models.CharField(db_index=True, default='региональное отделение', max_length=100, verbose_name='Региональное отделение')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'регионы',
            },
        ),
        migrations.CreateModel(
            name='Detachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('about', models.CharField(blank=True, default='', max_length=500, verbose_name='Описание')),
                ('emblem', models.ImageField(blank=True, upload_to='emblems/%Y/%m/%d', verbose_name='Эмблема')),
                ('social_vk', models.CharField(blank=True, default='https://vk.com/', max_length=50, verbose_name='Ссылка ВК')),
                ('social_tg', models.CharField(blank=True, default='https://', max_length=50, verbose_name='Ссылка Телеграм')),
                ('banner', models.ImageField(blank=True, upload_to='emblems/%Y/%m/%d', verbose_name='Баннер')),
                ('slogan', models.CharField(blank=True, default='', max_length=100, verbose_name='Девиз')),
                ('founding_date', models.DateField(blank=True, null=True, verbose_name='Дата основания')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='headquarters.area', verbose_name='Направление')),
                ('commander', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commander', to=settings.AUTH_USER_MODEL, verbose_name='Командир')),
            ],
            options={
                'verbose_name': 'Отряд',
                'verbose_name_plural': 'отряды',
            },
        ),
    ]
