# Generated by Django 4.2.7 on 2023-11-24 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import headquarters.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('headquarters', '0002_remove_region_branch_alter_detachment_commander_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centralheadquarter',
            options={'verbose_name': 'Структурная единица', 'verbose_name_plural': 'Структурные единицы'},
        ),
        migrations.AlterModelOptions(
            name='districtheadquarter',
            options={'verbose_name': 'Структурная единица', 'verbose_name_plural': 'Структурные единицы'},
        ),
        migrations.AlterModelOptions(
            name='educationalheadquarter',
            options={'verbose_name': 'Структурная единица', 'verbose_name_plural': 'Структурные единицы'},
        ),
        migrations.AlterModelOptions(
            name='localheadquarter',
            options={'verbose_name': 'Структурная единица', 'verbose_name_plural': 'Структурные единицы'},
        ),
        migrations.AlterModelOptions(
            name='regionalheadquarter',
            options={'verbose_name': 'Структурная единица', 'verbose_name_plural': 'Структурные единицы'},
        ),
        migrations.AddField(
            model_name='detachment',
            name='educational_headquarter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='detachments', to='headquarters.educationalheadquarter', verbose_name='Привязка к ШОО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='districtheadquarter',
            name='central_headquarter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='district_headquarters', to='headquarters.centralheadquarter', verbose_name='Привязка к ЦШ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationalheadquarter',
            name='educational_institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='headquarters', to='headquarters.educationalinstitution', verbose_name='Образовательная организация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationalheadquarter',
            name='local_headquarter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='educational_headquarters', to='headquarters.regionalheadquarter', verbose_name='Привязка к МШ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localheadquarter',
            name='regional_headquarter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='local_headquarters', to='headquarters.regionalheadquarter', verbose_name='Привязка к РШ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regionalheadquarter',
            name='district_headquarter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='regional_headquarters', to='headquarters.districtheadquarter', verbose_name='Привязка к ОШ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='centralheadquarter',
            name='banner',
            field=models.ImageField(blank=True, upload_to=headquarters.models.image_path, verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='centralheadquarter',
            name='commander',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Командир'),
        ),
        migrations.AlterField(
            model_name='centralheadquarter',
            name='emblem',
            field=models.ImageField(blank=True, upload_to=headquarters.models.image_path, verbose_name='Эмблема'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='banner',
            field=models.ImageField(blank=True, upload_to=headquarters.models.image_path, verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='commander',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Командир'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='emblem',
            field=models.ImageField(blank=True, upload_to=headquarters.models.image_path, verbose_name='Эмблема'),
        ),
        migrations.AlterField(
            model_name='districtheadquarter',
            name='banner',
            field=models.ImageField(blank=True, upload_to=headquarters.models.image_path, verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='districtheadquarter',
            name='commander',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Командир'),
        ),
        migrations.AlterField(
            model_name='districtheadquarter',
            name='emblem',
            field=models.ImageField(blank=True, upload_to=headquarters.models.image_path, verbose_name='Эмблема'),
        ),
        migrations.AlterField(
            model_name='educationalheadquarter',
            name='banner',
            field=models.ImageField(blank=True, upload_to=headquarters.models.image_path, verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='educationalheadquarter',
            name='commander',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Командир'),
        ),
        migrations.AlterField(
            model_name='educationalheadquarter',
            name='emblem',
            field=models.ImageField(blank=True, upload_to=headquarters.models.image_path, verbose_name='Эмблема'),
        ),
        migrations.AlterField(
            model_name='educationalinstitution',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='headquarters.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='localheadquarter',
            name='banner',
            field=models.ImageField(blank=True, upload_to=headquarters.models.image_path, verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='localheadquarter',
            name='commander',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Командир'),
        ),
        migrations.AlterField(
            model_name='localheadquarter',
            name='emblem',
            field=models.ImageField(blank=True, upload_to=headquarters.models.image_path, verbose_name='Эмблема'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='banner',
            field=models.ImageField(blank=True, upload_to=headquarters.models.image_path, verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='commander',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Командир'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='emblem',
            field=models.ImageField(blank=True, upload_to=headquarters.models.image_path, verbose_name='Эмблема'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='headquarters', to='headquarters.region', verbose_name='Регион'),
        ),
    ]
