# Generated by Django 4.2.7 on 2023-12-07 20:16

import django.db.models.deletion
import headquarters.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0002_centralheadquarter_commander_detachment_commander_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detachment',
            name='educational_institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='detachments', to='headquarters.educationalinstitution', verbose_name='Привязка к учебному заведению'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detachment',
            name='photo1',
            field=models.ImageField(blank=True, upload_to=headquarters.utils.image_path, verbose_name='Фото 1'),
        ),
        migrations.AddField(
            model_name='detachment',
            name='photo2',
            field=models.ImageField(blank=True, upload_to=headquarters.utils.image_path, verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='detachment',
            name='photo3',
            field=models.ImageField(blank=True, upload_to=headquarters.utils.image_path, verbose_name='Фото 3'),
        ),
        migrations.AddField(
            model_name='detachment',
            name='photo4',
            field=models.ImageField(blank=True, upload_to=headquarters.utils.image_path, verbose_name='Фото 4'),
        ),
        migrations.AddField(
            model_name='detachment',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='detachments', to='headquarters.region', verbose_name='Привязка к региону'),
            preserve_default=False,
        ),
    ]
