# Generated by Django 4.2.7 on 2023-11-24 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0003_alter_centralheadquarter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detachment',
            name='educational_headquarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detachments', to='headquarters.educationalheadquarter', verbose_name='Привязка к ШОО'),
        ),
    ]
