# Generated by Django 4.2.7 on 2023-12-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0003_detachment_educational_institution_detachment_photo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detachment',
            name='city',
            field=models.CharField(default=1, max_length=100, verbose_name='Город (нас. пункт)'),
            preserve_default=False,
        ),
    ]
