# Generated by Django 4.2.7 on 2023-12-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0005_alter_centralheadquarter_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralheadquarter',
            name='social_tg',
            field=models.CharField(max_length=50, verbose_name='Ссылка Телеграм'),
        ),
        migrations.AlterField(
            model_name='centralheadquarter',
            name='social_vk',
            field=models.CharField(max_length=50, verbose_name='Ссылка ВК'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='social_tg',
            field=models.CharField(max_length=50, verbose_name='Ссылка Телеграм'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='social_vk',
            field=models.CharField(max_length=50, verbose_name='Ссылка ВК'),
        ),
        migrations.AlterField(
            model_name='districtheadquarter',
            name='social_tg',
            field=models.CharField(max_length=50, verbose_name='Ссылка Телеграм'),
        ),
        migrations.AlterField(
            model_name='districtheadquarter',
            name='social_vk',
            field=models.CharField(max_length=50, verbose_name='Ссылка ВК'),
        ),
        migrations.AlterField(
            model_name='educationalheadquarter',
            name='social_tg',
            field=models.CharField(max_length=50, verbose_name='Ссылка Телеграм'),
        ),
        migrations.AlterField(
            model_name='educationalheadquarter',
            name='social_vk',
            field=models.CharField(max_length=50, verbose_name='Ссылка ВК'),
        ),
        migrations.AlterField(
            model_name='localheadquarter',
            name='social_tg',
            field=models.CharField(max_length=50, verbose_name='Ссылка Телеграм'),
        ),
        migrations.AlterField(
            model_name='localheadquarter',
            name='social_vk',
            field=models.CharField(max_length=50, verbose_name='Ссылка ВК'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='social_tg',
            field=models.CharField(max_length=50, verbose_name='Ссылка Телеграм'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='social_vk',
            field=models.CharField(max_length=50, verbose_name='Ссылка ВК'),
        ),
    ]
