# Generated by Django 4.2.7 on 2023-11-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0005_alter_centralheadquarter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationalinstitution',
            options={'verbose_name': 'Образовательная организация', 'verbose_name_plural': 'Образовательные организации'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
    ]
