# Generated by Django 4.2.7 on 2023-12-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0005_alter_centralheadquarter_name_alter_detachment_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlocalheadquarterposition',
            options={'verbose_name': 'Член местного штаба', 'verbose_name_plural': 'Члены местных штабов'},
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(blank=True, choices=[('no_position', 'Без должности'), ('comissioner', 'Комиссар'), ('master_methodologist', 'Мастер-методист'), ('specialist', 'Специалист'), ('commander', 'Командир'), ('central_commander', 'Коммандир центрального штаба'), ('district_commander', 'Коммандир окружного штаба'), ('regional_commander', 'Коммандир регионального штаба'), ('local_commander', 'Коммандир местного штаба'), ('edu_commander', 'Коммандир штаба образовательной организации'), ('detachment_commander', 'Коммандир отряда'), ('candidate', 'Кандидат'), ('fighter', 'Боец')], default='candidate', max_length=43, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='userlocalheadquarterposition',
            name='headquarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='headquarters.localheadquarter', verbose_name='Местный штаб'),
        ),
    ]
