# Generated by Django 4.2.7 on 2023-12-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0006_alter_centralheadquarter_social_tg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralheadquarter',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город (нас. пункт)'),
        ),
        migrations.AddField(
            model_name='districtheadquarter',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город (нас. пункт)'),
        ),
        migrations.AddField(
            model_name='educationalheadquarter',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город (нас. пункт)'),
        ),
        migrations.AddField(
            model_name='localheadquarter',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город (нас. пункт)'),
        ),
        migrations.AddField(
            model_name='regionalheadquarter',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город (нас. пункт)'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город (нас. пункт)'),
        ),
    ]
