# Generated by Django 4.2.7 on 2023-11-25 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import headquarters.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('headquarters', '0006_alter_educationalinstitution_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralheadquarter',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='centralheadquarter',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=headquarters.models.image_path, verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='centralheadquarter',
            name='commander',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Командир'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='centralheadquarter',
            name='emblem',
            field=models.ImageField(blank=True, null=True, upload_to=headquarters.models.image_path, verbose_name='Эмблема'),
        ),
        migrations.AlterField(
            model_name='centralheadquarter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='centralheadquarter',
            name='slogan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Девиз'),
        ),
        migrations.AlterField(
            model_name='centralheadquarter',
            name='social_tg',
            field=models.CharField(blank=True, default='https://', max_length=50, null=True, verbose_name='Ссылка Телеграм'),
        ),
        migrations.AlterField(
            model_name='centralheadquarter',
            name='social_vk',
            field=models.CharField(blank=True, default='https://vk.com/', max_length=50, null=True, verbose_name='Ссылка ВК'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=headquarters.models.image_path, verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='commander',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Командир'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detachment',
            name='emblem',
            field=models.ImageField(blank=True, null=True, upload_to=headquarters.models.image_path, verbose_name='Эмблема'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='slogan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Девиз'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='social_tg',
            field=models.CharField(blank=True, default='https://', max_length=50, null=True, verbose_name='Ссылка Телеграм'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='social_vk',
            field=models.CharField(blank=True, default='https://vk.com/', max_length=50, null=True, verbose_name='Ссылка ВК'),
        ),
        migrations.AlterField(
            model_name='districtheadquarter',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='districtheadquarter',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=headquarters.models.image_path, verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='districtheadquarter',
            name='commander',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Командир'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='districtheadquarter',
            name='emblem',
            field=models.ImageField(blank=True, null=True, upload_to=headquarters.models.image_path, verbose_name='Эмблема'),
        ),
        migrations.AlterField(
            model_name='districtheadquarter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='districtheadquarter',
            name='slogan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Девиз'),
        ),
        migrations.AlterField(
            model_name='districtheadquarter',
            name='social_tg',
            field=models.CharField(blank=True, default='https://', max_length=50, null=True, verbose_name='Ссылка Телеграм'),
        ),
        migrations.AlterField(
            model_name='districtheadquarter',
            name='social_vk',
            field=models.CharField(blank=True, default='https://vk.com/', max_length=50, null=True, verbose_name='Ссылка ВК'),
        ),
        migrations.AlterField(
            model_name='educationalheadquarter',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='educationalheadquarter',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=headquarters.models.image_path, verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='educationalheadquarter',
            name='commander',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Командир'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educationalheadquarter',
            name='emblem',
            field=models.ImageField(blank=True, null=True, upload_to=headquarters.models.image_path, verbose_name='Эмблема'),
        ),
        migrations.AlterField(
            model_name='educationalheadquarter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='educationalheadquarter',
            name='slogan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Девиз'),
        ),
        migrations.AlterField(
            model_name='educationalheadquarter',
            name='social_tg',
            field=models.CharField(blank=True, default='https://', max_length=50, null=True, verbose_name='Ссылка Телеграм'),
        ),
        migrations.AlterField(
            model_name='educationalheadquarter',
            name='social_vk',
            field=models.CharField(blank=True, default='https://vk.com/', max_length=50, null=True, verbose_name='Ссылка ВК'),
        ),
        migrations.AlterField(
            model_name='localheadquarter',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='localheadquarter',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=headquarters.models.image_path, verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='localheadquarter',
            name='commander',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Командир'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='localheadquarter',
            name='emblem',
            field=models.ImageField(blank=True, null=True, upload_to=headquarters.models.image_path, verbose_name='Эмблема'),
        ),
        migrations.AlterField(
            model_name='localheadquarter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='localheadquarter',
            name='slogan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Девиз'),
        ),
        migrations.AlterField(
            model_name='localheadquarter',
            name='social_tg',
            field=models.CharField(blank=True, default='https://', max_length=50, null=True, verbose_name='Ссылка Телеграм'),
        ),
        migrations.AlterField(
            model_name='localheadquarter',
            name='social_vk',
            field=models.CharField(blank=True, default='https://vk.com/', max_length=50, null=True, verbose_name='Ссылка ВК'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=headquarters.models.image_path, verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='commander',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Командир'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='emblem',
            field=models.ImageField(blank=True, null=True, upload_to=headquarters.models.image_path, verbose_name='Эмблема'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='slogan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Девиз'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='social_tg',
            field=models.CharField(blank=True, default='https://', max_length=50, null=True, verbose_name='Ссылка Телеграм'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='social_vk',
            field=models.CharField(blank=True, default='https://vk.com/', max_length=50, null=True, verbose_name='Ссылка ВК'),
        ),
    ]
