# Generated by Django 4.2.7 on 2023-11-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0007_alter_centralheadquarter_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
