# Generated by Django 4.2.7 on 2023-12-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0007_centralheadquarter_city_districtheadquarter_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralheadquarter',
            name='founding_date',
            field=models.DateField(auto_now=True, verbose_name='Дата основания'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='founding_date',
            field=models.DateField(auto_now=True, verbose_name='Дата основания'),
        ),
        migrations.AlterField(
            model_name='districtheadquarter',
            name='founding_date',
            field=models.DateField(auto_now=True, verbose_name='Дата основания'),
        ),
        migrations.AlterField(
            model_name='educationalheadquarter',
            name='founding_date',
            field=models.DateField(auto_now=True, verbose_name='Дата основания'),
        ),
        migrations.AlterField(
            model_name='localheadquarter',
            name='founding_date',
            field=models.DateField(auto_now=True, verbose_name='Дата основания'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='founding_date',
            field=models.DateField(auto_now=True, verbose_name='Дата основания'),
        ),
    ]
