# Generated by Django 4.2.7 on 2023-11-25 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('headquarters', '0009_alter_position_options_position_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercentralheadquarterposition',
            name='headquarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='headquarters.centralheadquarter', verbose_name='Центральный штаб'),
        ),
        migrations.AlterField(
            model_name='usercentralheadquarterposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_positions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userdetachmentposition',
            name='detachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='headquarters.detachment', verbose_name='Отряд'),
        ),
        migrations.AlterField(
            model_name='userdistrictheadquarterposition',
            name='headquarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='headquarters.districtheadquarter', verbose_name='Окружной штаб'),
        ),
        migrations.AlterField(
            model_name='userdistrictheadquarterposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_positions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='usereducationalheadquarterposition',
            name='headquarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='headquarters.educationalheadquarter', verbose_name='Образовательный штаб'),
        ),
        migrations.AlterField(
            model_name='usereducationalheadquarterposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_positions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userlocalheadquarterposition',
            name='headquarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='headquarters.localheadquarter', verbose_name='Локальный штаб'),
        ),
        migrations.AlterField(
            model_name='userlocalheadquarterposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_positions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userregionalheadquarterposition',
            name='headquarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='headquarters.regionalheadquarter', verbose_name='Региональный штаб'),
        ),
        migrations.AlterField(
            model_name='userregionalheadquarterposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_positions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
