# Generated by Django 4.2.7 on 2023-11-26 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('headquarters', '0010_alter_usercentralheadquarterposition_headquarter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetachmentposition',
            name='is_trusted',
            field=models.BooleanField(default=False, verbose_name='Доверенный'),
        ),
        migrations.AddField(
            model_name='userdetachmentposition',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='headquarters.position', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='userdetachmentposition',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_positions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercentralheadquarterposition',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='headquarters.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='userdistrictheadquarterposition',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='headquarters.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='usereducationalheadquarterposition',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='headquarters.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='userlocalheadquarterposition',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='headquarters.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='userregionalheadquarterposition',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='headquarters.position', verbose_name='Должность'),
        ),
    ]
