# Generated by Django 4.2.7 on 2023-11-26 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0011_userdetachmentposition_is_trusted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetachmentposition',
            old_name='detachment',
            new_name='headquarter',
        ),
    ]
