# Generated by Django 4.2.7 on 2023-12-15 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0012_regionalheadquarter_first_detachment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionalheadquarter',
            name='first_detachment_date',
        ),
        migrations.AlterField(
            model_name='centralheadquarter',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='centralheadquarter',
            name='slogan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Девиз'),
        ),
        migrations.AlterField(
            model_name='centralheadquarter',
            name='social_tg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка Телеграм'),
        ),
        migrations.AlterField(
            model_name='centralheadquarter',
            name='social_vk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка ВК'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='slogan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Девиз'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='social_tg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка Телеграм'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='social_vk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка ВК'),
        ),
        migrations.AlterField(
            model_name='districtheadquarter',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='districtheadquarter',
            name='slogan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Девиз'),
        ),
        migrations.AlterField(
            model_name='districtheadquarter',
            name='social_tg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка Телеграм'),
        ),
        migrations.AlterField(
            model_name='districtheadquarter',
            name='social_vk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка ВК'),
        ),
        migrations.AlterField(
            model_name='educationalheadquarter',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='educationalheadquarter',
            name='slogan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Девиз'),
        ),
        migrations.AlterField(
            model_name='educationalheadquarter',
            name='social_tg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка Телеграм'),
        ),
        migrations.AlterField(
            model_name='educationalheadquarter',
            name='social_vk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка ВК'),
        ),
        migrations.AlterField(
            model_name='localheadquarter',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='localheadquarter',
            name='slogan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Девиз'),
        ),
        migrations.AlterField(
            model_name='localheadquarter',
            name='social_tg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка Телеграм'),
        ),
        migrations.AlterField(
            model_name='localheadquarter',
            name='social_vk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка ВК'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='conference_date',
            field=models.DateField(default=datetime.date(2005, 1, 1), verbose_name='Дата учр. конференции регионального штаба'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='founding_date',
            field=models.CharField(max_length=4, verbose_name='Год основания'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='name_for_certificates',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Наименование штаба в Им. падеже (для справок)'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='registry_number',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Регистрационный номер в реестре молодежных и детских общественных объединений...'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='slogan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Девиз'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='social_tg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка Телеграм'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='social_vk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка ВК'),
        ),
    ]
