# Generated by Django 4.2.7 on 2023-11-26 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('headquarters', '0012_rename_detachment_userdetachmentposition_headquarter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercentralheadquarterposition',
            options={'verbose_name': 'Член центрального штаба', 'verbose_name_plural': 'Члены центрального штаба'},
        ),
        migrations.AlterModelOptions(
            name='userdetachmentposition',
            options={'verbose_name': 'Член отряда', 'verbose_name_plural': 'Члены отрядов'},
        ),
        migrations.AlterModelOptions(
            name='userdistrictheadquarterposition',
            options={'verbose_name': 'Член окружного штаба', 'verbose_name_plural': 'Члены окружных штабов'},
        ),
        migrations.AlterModelOptions(
            name='usereducationalheadquarterposition',
            options={'verbose_name': 'Член образовательного штаба', 'verbose_name_plural': 'Члены образовательных штабов'},
        ),
        migrations.AlterModelOptions(
            name='userlocalheadquarterposition',
            options={'verbose_name': 'Член локального штаба', 'verbose_name_plural': 'Члены локальных штабов'},
        ),
        migrations.AlterModelOptions(
            name='userregionalheadquarterposition',
            options={'verbose_name': 'Член регионального штаба', 'verbose_name_plural': 'Члены региональных штабов'},
        ),
        migrations.AlterField(
            model_name='usercentralheadquarterposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_position', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userdetachmentposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_position', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userdistrictheadquarterposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_position', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='usereducationalheadquarterposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_position', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userlocalheadquarterposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_position', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userregionalheadquarterposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_position', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
