# Generated by Django 4.2.7 on 2023-11-30 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('headquarters', '0013_alter_usercentralheadquarterposition_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetachmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='headquarters.detachment', verbose_name='Отряд, в который была подана заявка на вступление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, подавший заявку на вступление в отряд')),
            ],
            options={
                'verbose_name': 'Заявка на вступление в отряд',
                'verbose_name_plural': 'Заявки на вступление в отряды',
            },
        ),
        migrations.AddConstraint(
            model_name='userdetachmentapplication',
            constraint=models.UniqueConstraint(fields=('user', 'detachment'), name='unique_constraint'),
        ),
    ]
