# Generated by Django 4.2.7 on 2023-12-19 18:32

import datetime

import django.core.validators
import headquarters.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0013_remove_regionalheadquarter_first_detachment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centralheadquarter',
            name='founding_date',
        ),
        migrations.AddField(
            model_name='centralheadquarter',
            name='detachments_appearance_year',
            field=models.SmallIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='Дата появления студенческих отрядов в России (год)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centralheadquarter',
            name='rso_founding_congress_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 19, 18, 32, 53, 776546, tzinfo=datetime.timezone.utc), verbose_name='Дата первого учредительного съезда РСО'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detachment',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to=headquarters.utils.image_path, verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to=headquarters.utils.image_path, verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to=headquarters.utils.image_path, verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to=headquarters.utils.image_path, verbose_name='Фото 4'),
        ),
        migrations.AlterField(
            model_name='districtheadquarter',
            name='founding_date',
            field=models.DateField(verbose_name='Дата начала функционирования ОШ'),
        ),
        migrations.AlterField(
            model_name='localheadquarter',
            name='founding_date',
            field=models.DateField(verbose_name='Дата начала функционирования ОШ'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='founding_date',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='Год основания'),
        ),
    ]
