# Generated by Django 4.2.7 on 2023-12-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0014_alter_detachment_photo1_alter_detachment_photo2_and_more'),
        ('headquarters', '0014_remove_centralheadquarter_founding_date_and_more'),
    ]

    operations = [
    ]
