# Generated by Django 4.2.7 on 2024-01-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0018_alter_usercentralheadquarterposition_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(blank=True, max_length=43, null=True, verbose_name='Должность'),
        ),
    ]
