# Generated by Django 4.2.7 on 2024-01-12 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0019_alter_position_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regional_headquarters', to='headquarters.region', verbose_name='Регион'),
        ),
    ]
