# Generated by Django 4.2.7 on 2024-01-13 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0019_alter_position_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtheadquarter',
            name='central_headquarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='district_headquarters', to='headquarters.centralheadquarter', verbose_name='Привязка к ЦШ'),
        ),
    ]
