# Generated by Django 4.2.7 on 2024-01-13 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('headquarters', '0020_alter_districtheadquarter_central_headquarter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralheadquarter',
            name='commander',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_commander', to=settings.AUTH_USER_MODEL, verbose_name='Командир'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='commander',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_commander', to=settings.AUTH_USER_MODEL, verbose_name='Командир'),
        ),
        migrations.AlterField(
            model_name='districtheadquarter',
            name='commander',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_commander', to=settings.AUTH_USER_MODEL, verbose_name='Командир'),
        ),
        migrations.AlterField(
            model_name='educationalheadquarter',
            name='commander',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_commander', to=settings.AUTH_USER_MODEL, verbose_name='Командир'),
        ),
        migrations.AlterField(
            model_name='localheadquarter',
            name='commander',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_commander', to=settings.AUTH_USER_MODEL, verbose_name='Командир'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='commander',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_commander', to=settings.AUTH_USER_MODEL, verbose_name='Командир'),
        ),
    ]
