# Generated by Django 4.2.7 on 2024-01-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0020_alter_regionalheadquarter_region'),
        ('headquarters', '0023_alter_position_name'),
    ]

    operations = [
    ]
