# Generated by Django 4.2.7 on 2024-02-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0026_alter_educationalinstitution_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalinstitution',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Полное название образовательной организации'),
        ),
        migrations.AlterField(
            model_name='educationalinstitution',
            name='short_name',
            field=models.CharField(max_length=50, verbose_name='Короткое название образовательной организации (например, РГГУ)'),
        ),
    ]
