# Generated by Django 4.2.7 on 2024-02-05 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0027_alter_educationalinstitution_name_and_more'),
        ('headquarters', '0028_alter_detachment_educational_institution'),
    ]

    operations = [
    ]
