# Generated by Django 4.2.7 on 2024-02-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0028_alter_detachment_educational_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralheadquarter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='districtheadquarter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='educationalheadquarter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='localheadquarter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
