# Generated by Django 4.2.7 on 2024-02-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0029_merge_20240205_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalinstitution',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Полное название образовательной организации'),
        ),
        migrations.AlterField(
            model_name='educationalinstitution',
            name='short_name',
            field=models.CharField(max_length=100, verbose_name='Короткое название образовательной организации (например, РГГУ)'),
        ),
    ]
