# Generated by Django 4.2.7 on 2024-03-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0029_alter_centralheadquarter_name_alter_detachment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralheadquarter',
            name='slogan',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Девиз'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='slogan',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Девиз'),
        ),
        migrations.AlterField(
            model_name='districtheadquarter',
            name='slogan',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Девиз'),
        ),
        migrations.AlterField(
            model_name='educationalheadquarter',
            name='slogan',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Девиз'),
        ),
        migrations.AlterField(
            model_name='localheadquarter',
            name='slogan',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Девиз'),
        ),
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='slogan',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Девиз'),
        ),
    ]
