# Generated by Django 4.2.7 on 2024-03-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0030_alter_centralheadquarter_slogan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalheadquarter',
            name='requisites',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Реквизиты (для справок)'),
        ),
    ]
