# Generated by Django 4.2.7 on 2023-12-28 09:41

import django.db.models.deletion
import events.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventorganizationdata',
            options={'verbose_name': 'Организатор', 'verbose_name_plural': 'Организаторы мероприятий'},
        ),
        migrations.AlterField(
            model_name='eventadditionalissues',
            name='issue',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='eventdocument',
            name='document',
            field=models.FileField(default=1, upload_to=events.utils.document_path, verbose_name='Файл формата pdf, png, jpeg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventdocumentdata',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Расскажите, с какими документами необходимо просто ознакомиться, а какие скачать и заполнить'),
        ),
        migrations.AlterField(
            model_name='eventorganizationdata',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь-организатор'),
        ),
        migrations.AlterField(
            model_name='eventtimedata',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания мероприятия'),
        ),
        migrations.AlterField(
            model_name='eventtimedata',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания мероприятия'),
        ),
        migrations.AlterField(
            model_name='eventtimedata',
            name='event_duration_type',
            field=models.CharField(blank=True, choices=[('one_day', 'Однодневное'), ('multiple_days', 'Многодневное')], default='one_day', max_length=20, null=True, verbose_name='Продолжительность мероприятия'),
        ),
        migrations.AlterField(
            model_name='eventtimedata',
            name='registration_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания регистрации'),
        ),
        migrations.AlterField(
            model_name='eventtimedata',
            name='registration_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания регистрации'),
        ),
        migrations.AlterField(
            model_name='eventtimedata',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала мероприятия'),
        ),
        migrations.AlterField(
            model_name='eventtimedata',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала мероприятия'),
        ),
    ]
