# Generated by Django 4.2.7 on 2023-12-28 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventorganizationdata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdocumentdata',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_data', to='events.event', verbose_name='Мероприятие'),
        ),
    ]
