# Generated by Django 4.2.7 on 2023-12-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventdocumentdata_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventAdditionalIssues',
            new_name='EventAdditionalIssue',
        ),
    ]
