# Generated by Django 4.2.7 on 2023-12-28 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_eventadditionalissues_eventadditionalissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtimedata',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_data', to='events.event', verbose_name='Мероприятие'),
        ),
    ]
