# Generated by Django 4.2.7 on 2023-12-28 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventtimedata_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdocumentdata',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_data', to='events.event', verbose_name='Мероприятие'),
        ),
    ]
