# Generated by Django 4.2.7 on 2024-01-02 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0007_event_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventApplications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Подтверждено"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания заявки"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Дата обновления заявки"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_applications",
                        to="events.event",
                        verbose_name="Мероприятие",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на участие в мероприятии",
                "verbose_name_plural": "Заявки на участие в мероприятиях",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="EventIssueAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(verbose_name="Ответ")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="events.eventapplications",
                        verbose_name="Заявка",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="events.eventadditionalissue",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на вопрос участника мероприятия",
                "verbose_name_plural": "Ответы на вопросы участников мероприятий",
                "ordering": ["-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="eventissueanswer",
            constraint=models.UniqueConstraint(
                fields=("application", "issue"), name="unique_issue_answer"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventapplications",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="unique_event_application"
            ),
        ),
    ]
