# Generated by Django 4.2.7 on 2024-01-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='scale',
            field=models.CharField(choices=[('detachments', 'Отрядное'), ('educationals', 'Мероприятие ОО'), ('locals', 'Городское'), ('regionals', 'Региональное'), ('districts', 'Мероприятие ОО'), ('central', 'Отрядное ОО')], default='detachments', max_length=20, verbose_name='Масштаб'),
        ),
    ]
