# Generated by Django 4.2.7 on 2024-01-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_structural_units',
            field=models.CharField(blank=True, choices=[('detachments', 'Отряды'), ('educationals', 'Образовательные штабы'), ('locals', 'Местные штабы'), ('regionals', 'Региональные штабы'), ('districts', 'Окружные штабы'), ('central', 'Центральные штабы')], default='detachments', max_length=30, null=True, verbose_name='Объекты, имеющие возможность формировать групповые заявки'),
        ),
    ]
