# Generated by Django 4.2.7 on 2024-01-08 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("headquarters", "0019_alter_position_name"),
        ("events", "0011_multieventapplication_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="multieventapplication",
            name="unique_user_application",
        ),
        migrations.RemoveField(
            model_name="multieventapplication",
            name="user",
        ),
        migrations.AddField(
            model_name="multieventapplication",
            name="central_headquarter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="multi_event_applications",
                to="headquarters.centralheadquarter",
                verbose_name="Центральный штаб",
            ),
        ),
        migrations.AddField(
            model_name="multieventapplication",
            name="district_headquarter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="multi_event_applications",
                to="headquarters.districtheadquarter",
                verbose_name="Окружной штаб",
            ),
        ),
        migrations.AddField(
            model_name="multieventapplication",
            name="participants_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество участников"
            ),
        ),
        migrations.AddField(
            model_name="multieventapplication",
            name="regional_headquarter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="multi_event_applications",
                to="headquarters.regionalheadquarter",
                verbose_name="Региональный штаб",
            ),
        ),
        migrations.AddConstraint(
            model_name="multieventapplication",
            constraint=models.UniqueConstraint(
                fields=("event", "central_headquarter"),
                name="unique_central_headquarter_application",
            ),
        ),
        migrations.AddConstraint(
            model_name="multieventapplication",
            constraint=models.UniqueConstraint(
                fields=("event", "district_headquarter"),
                name="unique_district_headquarter_application",
            ),
        ),
        migrations.AddConstraint(
            model_name="multieventapplication",
            constraint=models.UniqueConstraint(
                fields=("event", "regional_headquarter"),
                name="unique_regional_headquarter_application",
            ),
        ),
    ]
