# Generated by Django 4.2.7 on 2024-01-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_available_structural_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='application_type',
            field=models.CharField(choices=[('Персональная', 'Персональная'), ('Групповая', 'Групповая'), ('Мультиэтапная', 'Мультиэтапная')], default='Групповая', max_length=20, verbose_name='Вид принимаемых к подаче на мероприятие заявок'),
        ),
        migrations.AlterField(
            model_name='event',
            name='available_structural_units',
            field=models.CharField(blank=True, choices=[('Отряды', 'Отряды'), ('Образовательные штабы', 'Образовательные штабы'), ('Местные штабы', 'Местные штабы'), ('Региональные штабы', 'Региональные штабы'), ('Окружные штабы', 'Окружные штабы'), ('Центральные штабы', 'Центральные штабы')], default='Отряды', max_length=30, null=True, verbose_name='Объекты, имеющие возможность формировать групповые заявки'),
        ),
        migrations.AlterField(
            model_name='event',
            name='direction',
            field=models.CharField(choices=[('Добровольческое', 'Добровольческое'), ('Образовательное', 'Образовательное'), ('Патриотическое', 'Патриотическое'), ('Спортивное', 'Спортивное'), ('Творческое', 'Творческое')], default='Добровольческое', max_length=20, verbose_name='Масштаб мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('Онлайн', 'Онлайн'), ('Оффлайн', 'Оффлайн')], default='Оффлайн', max_length=7, verbose_name='Тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='scale',
            field=models.CharField(choices=[('Отрядное', 'Отрядное'), ('Образовательное', 'Мероприятие Образовательного Штаба'), ('Городское', 'Городское'), ('Региональное', 'Региональное'), ('Окружное', 'Мероприятие Окружного Штаба'), ('Всероссийское', 'Мероприятие ЦШ')], default='Отрядное', max_length=20, verbose_name='Масштаб'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Активный', 'Активный'), ('Завершенный', 'Завершенный')], default='Активный', max_length=20, verbose_name='Статус мероприятия'),
        ),
        migrations.AlterField(
            model_name='eventtimedata',
            name='event_duration_type',
            field=models.CharField(blank=True, choices=[('Однодневное', 'Однодневное'), ('Многодневное', 'Многодневное')], default='Однодневное', max_length=20, null=True, verbose_name='Продолжительность мероприятия'),
        ),
    ]
