# Generated by Django 4.2.7 on 2024-01-16 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0012_alter_event_application_type_and_more"),
        (
            "events",
            "0012_remove_multieventapplication_unique_user_application_and_more",
        ),
    ]

    operations = []
