# Generated by Django 4.2.7 on 2024-02-12 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("headquarters", "0028_alter_detachment_educational_institution"),
        ("events", "0013_merge_20240116_1534"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="org_central_headquarter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="headquarters.centralheadquarter",
                verbose_name="Центральный штаб-организатор",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="org_detachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="headquarters.detachment",
                verbose_name="Отряд-организатор",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="org_district_headquarter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="headquarters.districtheadquarter",
                verbose_name="Окружной штаб-организатор",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="org_educational_headquarter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="headquarters.educationalheadquarter",
                verbose_name="Образовательный штаб-организатор",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="org_local_headquarter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="headquarters.localheadquarter",
                verbose_name="Местный штаб-организатор",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="org_regional_headquarter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="headquarters.regionalheadquarter",
                verbose_name="Региональный штаб-организатор",
            ),
        ),
    ]
