# Generated by Django 4.2.7 on 2024-01-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_сompetition_сompetitionparticipants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сompetitionapplications',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='сompetitionapplications',
            name='detachment',
        ),
        migrations.RemoveField(
            model_name='сompetitionapplications',
            name='junior_detachment',
        ),
        migrations.RemoveField(
            model_name='сompetitionparticipants',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='сompetitionparticipants',
            name='detachment',
        ),
        migrations.RemoveField(
            model_name='сompetitionparticipants',
            name='junior_detachment',
        ),
        migrations.DeleteModel(
            name='Сompetition',
        ),
        migrations.DeleteModel(
            name='СompetitionApplications',
        ),
        migrations.DeleteModel(
            name='СompetitionParticipants',
        ),
    ]
