# Generated by Django 4.2.7 on 2024-01-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0014_сompetition_сompetitionparticipants_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="сompetitionapplications",
            name="is_confirmed_by_junior",
            field=models.BooleanField(
                default=False, verbose_name="Подтверждено младшим отрядом"
            ),
        ),
    ]
