# Generated by Django 4.2.7 on 2024-03-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_groupeventapplicant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-id'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='eventadditionalissue',
            options={'ordering': ['-id'], 'verbose_name': 'Дополнительные вопросы мероприятия', 'verbose_name_plural': 'Дополнительные вопросы мероприятий'},
        ),
        migrations.AlterModelOptions(
            name='groupeventapplicant',
            options={'ordering': ['-id'], 'verbose_name': 'Участник группового мероприятия', 'verbose_name_plural': 'Участники групповых мероприятий'},
        ),
        migrations.RemoveConstraint(
            model_name='groupeventapplication',
            name='group_unique_central_headquarter_application',
        ),
        migrations.RemoveConstraint(
            model_name='groupeventapplication',
            name='group_unique_district_headquarter_application',
        ),
        migrations.RemoveConstraint(
            model_name='groupeventapplication',
            name='group_unique_regional_headquarter_application',
        ),
        migrations.RemoveConstraint(
            model_name='groupeventapplication',
            name='group_unique_local_headquarter_application',
        ),
        migrations.RemoveConstraint(
            model_name='groupeventapplication',
            name='group_unique_educational_headquarter_application',
        ),
        migrations.RemoveConstraint(
            model_name='groupeventapplication',
            name='group_unique_detachment_application',
        ),
        migrations.RemoveField(
            model_name='groupeventapplication',
            name='central_headquarter',
        ),
        migrations.RemoveField(
            model_name='groupeventapplication',
            name='detachment',
        ),
        migrations.RemoveField(
            model_name='groupeventapplication',
            name='district_headquarter',
        ),
        migrations.RemoveField(
            model_name='groupeventapplication',
            name='educational_headquarter',
        ),
        migrations.RemoveField(
            model_name='groupeventapplication',
            name='local_headquarter',
        ),
        migrations.RemoveField(
            model_name='groupeventapplication',
            name='regional_headquarter',
        ),
    ]
