# Generated by Django 4.2.7 on 2024-03-02 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_event_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupeventapplication',
            name='is_approved',
        ),
    ]
