# Generated by Django 4.2.7 on 2024-03-19 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0017_remove_groupeventapplication_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganizationdata',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь-организатор'),
            preserve_default=False,
        ),
    ]
