# Generated by Django 4.2.7 on 2024-03-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_eventorganizationdata_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес проведения (если мероприятие офлайн)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('Онлайн', 'Онлайн'), ('Офлайн', 'Офлайн')], default='Офлайн', max_length=7, verbose_name='Тип мероприятия'),
        ),
    ]
