# Generated by Django 4.2.7 on 2023-11-24 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregion',
            name='fact_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fact_region', to='headquarters.region', verbose_name='Регион проживания'),
        ),
        migrations.AddField(
            model_name='userregion',
            name='reg_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_region_region', to='headquarters.region', verbose_name='Регион прописки'),
        ),
    ]
