# Generated by Django 4.2.7 on 2023-11-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsouser',
            name='detachment',
        ),
        migrations.RemoveField(
            model_name='rsouser',
            name='position',
        ),
        migrations.AlterField(
            model_name='rsouser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
