# Generated by Django 4.2.7 on 2023-12-04 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignUserDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Документ, удостоверяющий личность')),
                ('snils', models.CharField(blank=True, max_length=15, null=True, verbose_name='СНИЛС')),
                ('inn', models.CharField(blank=True, max_length=15, null=True, verbose_name='ИНН')),
                ('foreign_pass_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='Серия и номер')),
                ('foreign_pass_whom', models.CharField(blank=True, max_length=15, null=True, verbose_name='Кем выдан')),
                ('foreign_pass_date', models.DateField(verbose_name='Дата выдачи')),
                ('work_book_num', models.CharField(blank=True, max_length=15, null=True, verbose_name='Трудовая книжка: серия, номер')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_documents', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Документы иностранного пользователя',
                'verbose_name_plural': 'Документы иностранных пользователей',
            },
        ),
        migrations.AddConstraint(
            model_name='foreignuserdocuments',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_foreign_documents'),
        ),
    ]
