# Generated by Django 4.2.7 on 2023-11-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_rsouser_date_of_birth'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userdocuments',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_documents'),
        ),
        migrations.AddConstraint(
            model_name='usereducation',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_education'),
        ),
        migrations.AddConstraint(
            model_name='usermedia',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_media'),
        ),
        migrations.AddConstraint(
            model_name='userprivacysettings',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_privacy_settings'),
        ),
        migrations.AddConstraint(
            model_name='userregion',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_region'),
        ),
    ]
