# Generated by Django 4.2.7 on 2023-12-04 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_foreignuserdocuments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('admin', 'Администратор'), ('commander', 'Коммандир штаба'), ('candidate', 'Кандидат'), ('fighter', 'Боец'), ('unregistered_user', 'Незарегистрированный пользователь'), ('unverified_user', 'Неверифицированный пользователь'), ('verified_user', 'Верифицированный пользователь'), ('trusted_user', 'Доверенный пользователь')], max_length=35, null=True, verbose_name='Роль пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='users_role', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользовательская роль',
                'verbose_name_plural': 'Пользовательские роли',
            },
        ),
    ]
