# Generated by Django 4.2.7 on 2023-12-10 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_foreignuserdocuments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMembershipLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата действия')),
                ('period', models.CharField(editable=False, max_length=20, verbose_name='Период')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Сообщение лога')),
                ('status_changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed_membership_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, изменивший статус оплаты другому')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог оплаты членского взноса',
                'verbose_name_plural': 'Логи оплаты членских взносов',
            },
        ),
    ]
