# Generated by Django 4.2.7 on 2023-11-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdocuments_unique_user_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsouser',
            name='position',
            field=models.CharField(blank=True, choices=[('no_position', 'Без должности'), ('comissioner', 'Комиссар'), ('master_methodologist', 'Мастер-методист'), ('specialist', 'Специалист'), ('commander', 'Командир')], max_length=20, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='inn',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='mil_reg_doc_ser_num',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер и серия документа воинского учета'),
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='pass_ser_num',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер и серия паспорта'),
        ),
    ]
