# Generated by Django 4.2.7 on 2023-12-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermembershiplogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembershiplogs',
            name='period',
            field=models.CharField(editable=False, max_length=30, verbose_name='Период'),
        ),
    ]
