# Generated by Django 4.2.7 on 2023-12-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usersroles_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersRoles',
        ),
    ]
