# Generated by Django 4.2.7 on 2023-11-23 16:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_rsouser_position_alter_userdocuments_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsouser',
            name='password',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(8, 'Пароль должен быть не менее 8 символов')], verbose_name='Пароль'),
        ),
        migrations.CreateModel(
            name='UserStatementDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.FileField(blank=True, null=True, upload_to='users/statement/%Y/%m/%d', verbose_name='Заявление на вступлении в РСО')),
                ('consent_personal_data', models.FileField(blank=True, null=True, upload_to='users/pdconsent/%Y/%m/%d', verbose_name='Согласие на обработку персональных данных')),
                ('consent_personal_data_representative', models.FileField(blank=True, null=True, upload_to='users/pdconsent_repr/%Y/%m/%d', verbose_name='Согласие официального представителя на обработку персональных данных несовершеннолетнего')),
                ('passport', models.FileField(blank=True, null=True, upload_to='users/passport/%Y/%m/%d', verbose_name='Паспорт гражданина РФ')),
                ('passport_representative', models.FileField(blank=True, null=True, upload_to='users/passport_repr/%Y/%m/%d', verbose_name='Паспорт законного представителя')),
                ('snils_file', models.FileField(blank=True, null=True, upload_to='users/snils/%Y/%m/%d', verbose_name='СНИЛС')),
                ('inn_file', models.FileField(blank=True, null=True, upload_to='users/inn/%Y/%m/%d', verbose_name='ИИН')),
                ('employment_document', models.FileField(blank=True, null=True, upload_to='users/inn/%Y/%m/%d', verbose_name='Трудовая книжка')),
                ('military_document', models.FileField(blank=True, null=True, upload_to='users/militarydoc/%Y/%m/%d', verbose_name='Военный билет')),
                ('international_passport', models.FileField(blank=True, null=True, upload_to='users/intpassport/%Y/%m/%d', verbose_name='Загранпаспорт')),
                ('additional_document', models.FileField(blank=True, null=True, upload_to='users/adddoc/%Y/%m/%d', verbose_name='Дополнительный документ')),
                ('rso_info_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='Откуда вы узнали про РСО?')),
                ('personal_data_agreement', models.BooleanField(default=False, verbose_name='Даю согласие на обработку моих персональных данных в соответствии с законом от 27.07.2006 года № 152-ФЗ «О  персональных данных», на условиях и для целей, определенных в Согласии на обработку персональных данных')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявление на вступление в РСО пользователя',
                'verbose_name_plural': 'Заявления на вступление в РСО пользователей',
            },
        ),
        migrations.AddConstraint(
            model_name='userstatementdocuments',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_statement'),
        ),
    ]
