# Generated by Django 4.2.7 on 2023-12-19 18:32

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usermembershiplogs_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsouser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.image_path, verbose_name='Баннер личной страницы'),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.image_path, verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.image_path, verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.image_path, verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.image_path, verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.image_path, verbose_name='Фото 4'),
        ),
    ]
