# Generated by Django 4.2.7 on 2023-12-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_usersroles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsouser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
