# Generated by Django 4.2.7 on 2023-11-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usermedia_banner_alter_usermedia_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsouser',
            name='unit_type',
        ),
    ]
