# Generated by Django 4.2.7 on 2023-12-13 10:56

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_usersroles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsouser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[users.models.unique_email_validator], verbose_name='Email'),
        ),
    ]
