# Generated by Django 4.2.7 on 2023-11-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_rsouser_password_userstatementdocuments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsouser',
            name='password',
            field=models.CharField(max_length=12),
        ),
    ]
