# Generated by Django 4.2.7 on 2023-12-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_rsouser_email_alter_usermedia_banner_and_more'),
        ('users', '0006_delete_usermembercertrequest'),
    ]

    operations = [
    ]
