# Generated by Django 4.2.7 on 2023-11-25 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_rsouser_unit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usereducation',
            name='study_group',
        ),
    ]
