# Generated by Django 4.2.7 on 2023-12-27 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_rsouser_email'),
        ('users', '0007_merge_20231221_1129'),
    ]

    operations = [
    ]
