# Generated by Django 4.2.7 on 2023-12-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_usercertinternal_user_delete_usercertexternal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercert',
            name='position_procuration',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Должность подписывающего лица, доверенность'),
        ),
        migrations.AlterField(
            model_name='membercert',
            name='signatory',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ФИО подписывающего лица'),
        ),
    ]
