# Generated by Django 4.2.7 on 2023-12-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_membercert_position_procuration_and_more'),
        ('users', '0009_remove_usercertinternal_user_delete_usercertexternal_and_more'),
    ]

    operations = [
    ]
