# Generated by Django 4.2.7 on 2023-11-26 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0013_alter_usercentralheadquarterposition_options_and_more'),
        ('users', '0009_usersparent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersparent',
            options={'verbose_name': 'Законный представитель несовершеннолетнего'},
        ),
        migrations.AlterField(
            model_name='usersparent',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Улица, дом, квартира'),
        ),
        migrations.AlterField(
            model_name='usersparent',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='usersparent',
            name='parent_date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='usersparent',
            name='parent_first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='usersparent',
            name='parent_last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='usersparent',
            name='parent_patronymic_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='usersparent',
            name='parent_phone_number',
            field=models.CharField(blank=True, default='+7', max_length=30, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='usersparent',
            name='passport_authority',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='usersparent',
            name='passport_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='usersparent',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер и серия'),
        ),
        migrations.AlterField(
            model_name='usersparent',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='headquarters.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='usersparent',
            name='relationship',
            field=models.CharField(blank=True, choices=[('father', 'Отец'), ('mother', 'Мать'), ('guardian', 'Опекун')], max_length=8, null=True, verbose_name='Кем является'),
        ),
    ]
