# Generated by Django 4.2.7 on 2023-11-27 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_usersparent_options_alter_usersparent_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalEduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_institution', models.CharField(blank=True, max_length=200, null=True, verbose_name='Образовательная организация')),
                ('years_of_study', models.DurationField(blank=True, null=True, verbose_name='Годы обучения')),
                ('exam_score', models.CharField(blank=True, max_length=20, null=True, verbose_name='Оценка')),
                ('qualification', models.CharField(blank=True, max_length=100, null=True, verbose_name='Квалификация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proffesional_education', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Дополнительное профессиональное образование.',
                'verbose_name_plural': 'Дополнительные профессиональные образования.',
            },
        ),
    ]
