# Generated by Django 4.2.7 on 2023-12-01 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_usersparent_options_alter_usersparent_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersparent',
            options={'verbose_name': 'Законный представитель несовершеннолетнего', 'verbose_name_plural': 'Законные представители несовершеннолетних'},
        ),
        migrations.CreateModel(
            name='UserVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veirification', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, подавший заявку на верификацию')),
            ],
            options={
                'verbose_name': 'Заявка на верификацию',
                'verbose_name_plural': 'Заявки на верификацию',
            },
        ),
    ]
