# Generated by Django 4.2.7 on 2023-12-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_usereducation_study_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocuments',
            name='snils',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='СНИЛС'),
        ),
    ]
