# Generated by Django 4.2.7 on 2023-11-27 19:06

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_professionaleduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaleduction',
            name='years_of_study',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[users.utils.validate_years], verbose_name='Годы обучения'),
        ),
    ]
