# Generated by Django 4.2.7 on 2023-12-28 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_userdocuments_snils'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaleduction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_education', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
