# Generated by Django 4.2.7 on 2023-12-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0016_merge_20231227_2119'),
        ('users', '0013_alter_professionaleduction_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForeignUserDocuments',
            new_name='UserForeignDocuments',
        ),
        migrations.RenameModel(
            old_name='UsersParent',
            new_name='UserParent',
        ),
        migrations.RenameModel(
            old_name='ProfessionalEduction',
            new_name='UserProfessionalEducation',
        ),
    ]
