# Generated by Django 4.2.7 on 2023-12-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_foreignuserdocuments_userforeigndocuments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userforeigndocuments',
            name='foreign_pass_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
    ]
