# Generated by Django 4.2.7 on 2023-12-31 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_userforeigndocuments_foreign_pass_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMemberCertLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата действия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Сообщение лога')),
                ('cert_type', models.CharField(max_length=50, verbose_name='Тип справки')),
                ('cert_issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_membercert_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, выдавший справку')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membercert_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог выдачи справки о членстве в РСО.',
                'verbose_name_plural': 'Логи выдачи справок о членстве в РСО.',
            },
        ),
    ]
