# Generated by Django 4.2.7 on 2024-01-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_userdocuments_russian_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercert',
            name='number',
            field=models.CharField(default=' ', max_length=40, verbose_name='Номер справки'),
        ),
        migrations.AlterField(
            model_name='userprivacysettings',
            name='privacy_about',
            field=models.CharField(choices=[('Все', 'Все'), ('Члены отряда', 'Члены отряда'), ('Руководство', 'Руководство')], default='all', max_length=20, verbose_name='Кто видит информацию "Обо мне"'),
        ),
        migrations.AlterField(
            model_name='userprivacysettings',
            name='privacy_email',
            field=models.CharField(choices=[('Все', 'Все'), ('Члены отряда', 'Члены отряда'), ('Руководство', 'Руководство')], default='all', max_length=20, verbose_name='Кто видит электронную почту'),
        ),
        migrations.AlterField(
            model_name='userprivacysettings',
            name='privacy_photo',
            field=models.CharField(choices=[('Все', 'Все'), ('Члены отряда', 'Члены отряда'), ('Руководство', 'Руководство')], default='all', max_length=20, verbose_name='Кто видит мои фотографии'),
        ),
        migrations.AlterField(
            model_name='userprivacysettings',
            name='privacy_social',
            field=models.CharField(choices=[('Все', 'Все'), ('Члены отряда', 'Члены отряда'), ('Руководство', 'Руководство')], default='all', max_length=20, verbose_name='Кто видит ссылки на соц.сети'),
        ),
        migrations.AlterField(
            model_name='userprivacysettings',
            name='privacy_telephone',
            field=models.CharField(choices=[('Все', 'Все'), ('Члены отряда', 'Члены отряда'), ('Руководство', 'Руководство')], default='all', max_length=20, verbose_name='Кто видит номер телефона'),
        ),
    ]
