# Generated by Django 4.2.7 on 2024-02-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_userdocuments_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereducation',
            name='study_specialty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Специальность'),
        ),
    ]
