# Generated by Django 4.2.7 on 2024-02-05 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_usereducation_study_specialty'),
        ('users', '0021_userverificationlogs'),
    ]

    operations = [
    ]
