# Generated by Django 4.2.7 on 2024-02-12 21:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_alter_userprivacysettings_privacy_about_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membercert",
            options={
                "verbose_name": "Выданная справка о членстве в РСО",
                "verbose_name_plural": "Выданные справки о членстве в РСО",
            },
        ),
        migrations.AlterModelOptions(
            name="usermembercertlogs",
            options={
                "verbose_name": "Лог выдачи справки о членстве в РСО",
                "verbose_name_plural": "Логи выдачи справок о членстве в РСО",
            },
        ),
        migrations.AlterModelOptions(
            name="userverificationlogs",
            options={
                "verbose_name": "Лог верификации юзеров",
                "verbose_name_plural": "Логи верификации юзеров",
            },
        ),
    ]
