# Generated by Django 4.2.7 on 2024-03-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_membercert_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocuments',
            name='pass_address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Место регистрации по паспорту'),
        ),
        migrations.AlterField(
            model_name='userforeigndocuments',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Документ, удостоверяющий личность'),
        ),
        migrations.AlterField(
            model_name='userparent',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Улица, дом, квартира'),
        ),
        migrations.AlterField(
            model_name='userparent',
            name='passport_authority',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='userregion',
            name='reg_house',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Улица, дом, кв. прописки'),
        ),
    ]
