# Generated by Django 4.2.7 on 2024-03-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_userdocuments_pass_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsouser',
            name='is_rso_member',
            field=models.BooleanField(default=False, verbose_name='Статус членства в РСО'),
        ),
    ]
