# Generated by Django 4.2.7 on 2024-03-24 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeroption',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='attempt',
            options={'verbose_name': 'Попытка пользователя', 'verbose_name_plural': 'Попытки пользователей'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Ответ пользователя', 'verbose_name_plural': 'Ответы пользователей'},
        ),
        migrations.AddField(
            model_name='attempt',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество баллов'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='category',
            field=models.CharField(choices=[('university', 'Тест по обучению (корпоративный университет)'), ('safety', 'Тест по безопасности и охране труда')], default='university', max_length=20, verbose_name='Категория попытки'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время начала попытки'),
        ),
        migrations.AlterField(
            model_name='question',
            name='block',
            field=models.CharField(choices=[('1', 'История РСО'), ('2', 'Нормативные документы'), ('3', 'Компетенции командного состава и отряда'), ('4', 'Решение кейсовых ситуаций'), ('5', 'Охрана труда')], default='1', max_length=2, verbose_name='Блок вопросов'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.answeroption', verbose_name='Вариант ответа'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.attempt', verbose_name='Попытка'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='Вопрос'),
        ),
    ]
