# Generated by Django 4.2.7 on 2024-03-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_answeroption_options_alter_attempt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
