# Generated by Django 4.2.7 on 2024-02-16 18:53

import competitions.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "headquarters",
            "0029_alter_centralheadquarter_name_alter_detachment_name_and_more",
        ),
        ("competitions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participation_in_district_and_interregional_events",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Оценка"),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_scores",
                        to="competitions.competitions",
                        verbose_name="Конкурс",
                    ),
                ),
                (
                    "detachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_scores",
                        to="headquarters.detachment",
                        verbose_name="Отряд",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParticipationInDistrAndInterregionalEventsReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Подтверждено"),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participation_in_district_and_interregional_events_reports",
                        to="competitions.competitions",
                        verbose_name="Конкурс",
                    ),
                ),
                (
                    "detachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participation_in_district_and_interregional_events_reports",
                        to="headquarters.detachment",
                        verbose_name="Отряд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчет о участии в окружных и межрегиональных мероприятиях",
                "verbose_name_plural": "Отчеты о участии в окружных и межрегиональных мероприятиях",
                "ordering": ["-competition__id"],
            },
        ),
        migrations.CreateModel(
            name="ParticipationInDistrAndInterregionalEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        max_length=255, verbose_name="Название мероприятия"
                    ),
                ),
                (
                    "certificate_scans",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=competitions.utils.get_certificate_scans_path,
                        verbose_name="Сканы сертификатов",
                    ),
                ),
                (
                    "number_of_participants",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Количество участников",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания заявки"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="competitions.participationindistrandinterregionaleventsreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участие в окружных и межрегиональных  мероприятиях",
            },
        ),
        migrations.CreateModel(
            name="LinksOfParticipationInDistrAndInterregionalEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField(max_length=500, verbose_name="Ссылка")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="competitions.participationindistrandinterregionalevents",
                        verbose_name="Участие в окружных и межрегиональных мероприятиях",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка на фотоотчет участия СО в окружном или межрегиональном мероприятии",
                "verbose_name_plural": "Ссылки на фотоотчет участия СО в окружных и межрегиональных мероприятиях",
            },
        ),
        migrations.AddConstraint(
            model_name="participationindistrandinterregionaleventsreport",
            constraint=models.UniqueConstraint(
                fields=("competition", "detachment"),
                name="unique_participation_in_district_and_interregional_events_report",
            ),
        ),
    ]
