# Generated by Django 4.2.7 on 2024-02-21 07:41

import competitions.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "headquarters",
            "0029_alter_centralheadquarter_name_alter_detachment_name_and_more",
        ),
        ("competitions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participation_in_distr_and_interreg_events",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Общее количество участий"
                    ),
                ),
                (
                    "participation_in_all_russian_events",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Общее количество участий"
                    ),
                ),
                (
                    "prize_places_in_distr_and_interreg_events",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Среднее место"
                    ),
                ),
                (
                    "prize_places_in_all_russian_events",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Среднее место"
                    ),
                ),
                (
                    "prize_places_in_distr_and_interreg_labor_projects",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Среднее место"
                    ),
                ),
                (
                    "prize_places_in_all_russian_labor_projects",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Среднее место"
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_scores",
                        to="competitions.competitions",
                        verbose_name="Конкурс",
                    ),
                ),
                (
                    "detachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_scores",
                        to="headquarters.detachment",
                        verbose_name="Отряд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка отряда",
                "verbose_name_plural": "Оценки отрядов",
            },
        ),
        migrations.CreateModel(
            name="PrizePlacesInDistrAndInterregLaborProjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        max_length=255, verbose_name="Название мероприятия"
                    ),
                ),
                (
                    "certificate_scans",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=competitions.utils.get_certificate_scans_path,
                        verbose_name="Сканы сертификатов",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания заявки"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Подтверждено"),
                ),
                (
                    "prize_place",
                    models.IntegerField(
                        choices=[
                            (1, "Первое место"),
                            (2, "Второе место"),
                            (3, "Третье место"),
                        ],
                        verbose_name="Призовое место",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="competitions.competitions",
                        verbose_name="Конкурс",
                    ),
                ),
                (
                    "detachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.detachment",
                        verbose_name="Отряд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Призовое место в окружных и межрегиональных трудовых проектах",
                "verbose_name_plural": "Призовые места в окружных и межрегиональных трудовых проектах",
                "ordering": ["-competition__id"],
            },
        ),
        migrations.CreateModel(
            name="PrizePlacesInDistrAndInterregEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        max_length=255, verbose_name="Название мероприятия"
                    ),
                ),
                (
                    "certificate_scans",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=competitions.utils.get_certificate_scans_path,
                        verbose_name="Сканы сертификатов",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания заявки"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Подтверждено"),
                ),
                (
                    "prize_place",
                    models.IntegerField(
                        choices=[
                            (1, "Первое место"),
                            (2, "Второе место"),
                            (3, "Третье место"),
                        ],
                        verbose_name="Призовое место",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="competitions.competitions",
                        verbose_name="Конкурс",
                    ),
                ),
                (
                    "detachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.detachment",
                        verbose_name="Отряд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Призовое место в окружных и межрегиональных мероприятиях и конкурсах РСО",
                "verbose_name_plural": "Призовые места в окружных и межрегиональных мероприятиях и конкурсах РСО",
                "ordering": ["-competition__id"],
            },
        ),
        migrations.CreateModel(
            name="PrizePlacesInAllRussianLaborProjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        max_length=255, verbose_name="Название мероприятия"
                    ),
                ),
                (
                    "certificate_scans",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=competitions.utils.get_certificate_scans_path,
                        verbose_name="Сканы сертификатов",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания заявки"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Подтверждено"),
                ),
                (
                    "prize_place",
                    models.IntegerField(
                        choices=[
                            (1, "Первое место"),
                            (2, "Второе место"),
                            (3, "Третье место"),
                        ],
                        verbose_name="Призовое место",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="competitions.competitions",
                        verbose_name="Конкурс",
                    ),
                ),
                (
                    "detachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.detachment",
                        verbose_name="Отряд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Призовое место на всероссийскихтрудовых проектах",
                "verbose_name_plural": "Призовые места на всероссийских трудовых проектах",
                "ordering": ["-competition__id"],
            },
        ),
        migrations.CreateModel(
            name="PrizePlacesInAllRussianEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        max_length=255, verbose_name="Название мероприятия"
                    ),
                ),
                (
                    "certificate_scans",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=competitions.utils.get_certificate_scans_path,
                        verbose_name="Сканы сертификатов",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания заявки"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Подтверждено"),
                ),
                (
                    "prize_place",
                    models.IntegerField(
                        choices=[
                            (1, "Первое место"),
                            (2, "Второе место"),
                            (3, "Третье место"),
                        ],
                        verbose_name="Призовое место",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="competitions.competitions",
                        verbose_name="Конкурс",
                    ),
                ),
                (
                    "detachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.detachment",
                        verbose_name="Отряд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Призовое место во всероссийских мероприятиях и конкурсах РСО",
                "verbose_name_plural": "Призовые места во всероссийских мероприятиях и конкурсах РСО",
                "ordering": ["-competition__id"],
            },
        ),
        migrations.CreateModel(
            name="ParticipationInDistrAndInterregEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        max_length=255, verbose_name="Название мероприятия"
                    ),
                ),
                (
                    "certificate_scans",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=competitions.utils.get_certificate_scans_path,
                        verbose_name="Сканы сертификатов",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания заявки"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Подтверждено"),
                ),
                (
                    "number_of_participants",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Количество участников",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="competitions.competitions",
                        verbose_name="Конкурс",
                    ),
                ),
                (
                    "detachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.detachment",
                        verbose_name="Отряд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участие в окружных и межрегиональных мероприятиях",
                "verbose_name_plural": "Участия в окружных и межрегиональных мероприятиях",
                "ordering": ["-competition__id"],
            },
        ),
        migrations.CreateModel(
            name="ParticipationInAllRussianEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        max_length=255, verbose_name="Название мероприятия"
                    ),
                ),
                (
                    "certificate_scans",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=competitions.utils.get_certificate_scans_path,
                        verbose_name="Сканы сертификатов",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания заявки"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Подтверждено"),
                ),
                (
                    "number_of_participants",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Количество участников",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="competitions.competitions",
                        verbose_name="Конкурс",
                    ),
                ),
                (
                    "detachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.detachment",
                        verbose_name="Отряд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участие во всероссийских мероприятиях",
                "verbose_name_plural": "Участия во всероссийских мероприятиях",
                "ordering": ["-competition__id"],
            },
        ),
        migrations.CreateModel(
            name="LinksOfParticipationInDistrAndInterregEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField(max_length=500, verbose_name="Ссылка")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="competitions.participationindistrandinterregevents",
                        verbose_name="Участие в окружных и межрегиональных мероприятиях",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка на фотоотчет участия СО в окружном или межрегиональном мероприятии",
                "verbose_name_plural": "Ссылки на фотоотчет участия СО в окружных и межрегиональных мероприятиях",
            },
        ),
        migrations.CreateModel(
            name="LinksOfParticipationInAllRussianEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField(max_length=500, verbose_name="Ссылка")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="competitions.participationinallrussianevents",
                        verbose_name="Участие во всероссийских мероприятиях",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка на фотоотчет участия СО во всероссийском мероприятии",
                "verbose_name_plural": "Ссылки на фотоотчет участия СО во всероссийских мероприятиях",
            },
        ),
        migrations.AddConstraint(
            model_name="score",
            constraint=models.UniqueConstraint(
                fields=("detachment", "competition"), name="unique_competition_score"
            ),
        ),
        migrations.AddConstraint(
            model_name="prizeplacesindistrandinterreglaborprojects",
            constraint=models.UniqueConstraint(
                fields=("competition", "detachment", "event_name"),
                name="unique_prize_places_in_distr_and_interreg_labor_projects",
            ),
        ),
        migrations.AddConstraint(
            model_name="prizeplacesindistrandinterregevents",
            constraint=models.UniqueConstraint(
                fields=("competition", "detachment", "event_name"),
                name="unique_prize_places_in_distr_and_interreg_events",
            ),
        ),
        migrations.AddConstraint(
            model_name="prizeplacesinallrussianlaborprojects",
            constraint=models.UniqueConstraint(
                fields=("competition", "detachment", "event_name"),
                name="unique_prize_places_in_all_russian_labor_projects",
            ),
        ),
        migrations.AddConstraint(
            model_name="prizeplacesinallrussianevents",
            constraint=models.UniqueConstraint(
                fields=("competition", "detachment", "event_name"),
                name="unique_prize_places_in_all_russian_events",
            ),
        ),
        migrations.AddConstraint(
            model_name="participationindistrandinterregevents",
            constraint=models.UniqueConstraint(
                fields=("competition", "detachment", "event_name"),
                name="unique_participation_in_distr_and_interreg_events",
            ),
        ),
        migrations.AddConstraint(
            model_name="participationinallrussianevents",
            constraint=models.UniqueConstraint(
                fields=("competition", "detachment", "event_name"),
                name="unique_participation_in_all_russian_events",
            ),
        ),
        migrations.AddConstraint(
            model_name="linksofparticipationindistrandinterregevents",
            constraint=models.UniqueConstraint(
                fields=("event", "link"),
                name="unique_event_link_distr_and_interreg_events",
            ),
        ),
        migrations.AddConstraint(
            model_name="linksofparticipationinallrussianevents",
            constraint=models.UniqueConstraint(
                fields=("event", "link"), name="unique_event_link_all_russian_events"
            ),
        ),
    ]
