# Generated by Django 4.2.7 on 2024-03-17 02:33

import competitions.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "headquarters",
            "0029_alter_centralheadquarter_name_alter_detachment_name_and_more",
        ),
        ("competitions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Q13DetachmentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_competition_reports",
                        to="competitions.competitions",
                    ),
                ),
                (
                    "detachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_detachment_reports",
                        to="headquarters.detachment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Q7TandemRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.PositiveSmallIntegerField(
                        default=12, verbose_name="Итоговое место по показателю"
                    ),
                ),
                (
                    "detachment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_main_detachment",
                        to="headquarters.detachment",
                        verbose_name="Отряд-наставник",
                    ),
                ),
                (
                    "junior_detachment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_junior_detachment",
                        to="headquarters.detachment",
                        verbose_name="Младший отряд",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Q7Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Общее количество участий"
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_competition_reports",
                        to="competitions.competitions",
                    ),
                ),
                (
                    "detachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_detachment_reports",
                        to="headquarters.detachment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Q7Ranking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.PositiveSmallIntegerField(
                        default=6,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="Итоговое место по показателю",
                    ),
                ),
                (
                    "detachment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.detachment",
                        verbose_name="Отряд",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Q7",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        max_length=255, verbose_name="Название мероприятия"
                    ),
                ),
                (
                    "certificate_scans",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=competitions.utils.get_certificate_scans_path,
                        verbose_name="Сканы сертификатов",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания заявки"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Подтверждено"),
                ),
                (
                    "number_of_participants",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Количество участников",
                    ),
                ),
                (
                    "detachment_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participation_data",
                        to="competitions.q7report",
                        verbose_name="Отчет отряда",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участие в окружных и межрегиональных мероприятиях",
                "verbose_name_plural": "Участия в окружных и межрегиональных мероприятиях",
            },
        ),
        migrations.CreateModel(
            name="Q18TandemRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.PositiveSmallIntegerField(
                        verbose_name="Итоговое место по показателю"
                    ),
                ),
                (
                    "detachment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_main_detachment",
                        to="headquarters.detachment",
                        verbose_name="Отряд-наставник",
                    ),
                ),
                (
                    "junior_detachment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_junior_detachment",
                        to="headquarters.detachment",
                        verbose_name="Младший отряд",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Q18Ranking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.PositiveSmallIntegerField(
                        verbose_name="Итоговое место по показателю"
                    ),
                ),
                (
                    "detachment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.detachment",
                        verbose_name="Отряд",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Q18DetachmentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "participants_number",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                        verbose_name="Количество бойцов, принявших участие во Всероссийском дне ударного труда",
                    ),
                ),
                ("june_15_detachment_members", models.PositiveSmallIntegerField()),
                ("score", models.FloatField(verbose_name="Очки")),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_competition_reports",
                        to="competitions.competitions",
                    ),
                ),
                (
                    "detachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_detachment_reports",
                        to="headquarters.detachment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Q13TandemRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.PositiveSmallIntegerField(
                        default=12, verbose_name="Итоговое место по показателю"
                    ),
                ),
                (
                    "detachment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_main_detachment",
                        to="headquarters.detachment",
                        verbose_name="Отряд-наставник",
                    ),
                ),
                (
                    "junior_detachment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_junior_detachment",
                        to="headquarters.detachment",
                        verbose_name="Младший отряд",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Q13Ranking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.PositiveSmallIntegerField(
                        default=6,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="Итоговое место по показателю",
                    ),
                ),
                (
                    "detachment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.detachment",
                        verbose_name="Отряд",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Q13EventOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("Спортивное", "Спортивное"),
                            ("Интеллектуальное", "Интеллектуальное"),
                            ("Творческое", "Творческое"),
                            ("Волонтерское", "Волонтерское"),
                            ("Внутреннее", "Внутреннее"),
                        ],
                        default="Внутреннее",
                        max_length=16,
                        verbose_name="Тип мероприятия",
                    ),
                ),
                (
                    "event_link",
                    models.URLField(max_length=500, verbose_name="Ссылка на пуб."),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "detachment_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_data",
                        to="competitions.q13detachmentreport",
                        verbose_name="Отчет отряда",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LinksQ7",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField(max_length=500, verbose_name="Ссылка")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="competitions.q7",
                        verbose_name="Участие в окружных и межрегиональных мероприятиях",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка на фотоотчет участия СО в окружном или межрегиональном мероприятии",
                "verbose_name_plural": "Ссылки на фотоотчет участия СО в окружных и межрегиональных мероприятиях",
            },
        ),
        migrations.AddConstraint(
            model_name="q7",
            constraint=models.UniqueConstraint(
                fields=("detachment_report", "event_name"),
                name="unique_participation_in_distr_and_interreg_events",
            ),
        ),
        migrations.AddConstraint(
            model_name="linksq7",
            constraint=models.UniqueConstraint(
                fields=("event", "link"),
                name="unique_event_link_distr_and_interreg_events",
            ),
        ),
    ]
