# Generated by Django 4.2.7 on 2024-03-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0002_q13detachmentreport_q7tandemranking_q7report_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="q13ranking",
            options={
                "verbose_name": "Места по 13 показателю",
                "verbose_name_plural": "Места по 13 показателю",
            },
        ),
        migrations.AlterModelOptions(
            name="q13tandemranking",
            options={
                "verbose_name": "Тандем-места по 13 показателю",
                "verbose_name_plural": "Тандем-места по 13 показателю",
            },
        ),
        migrations.AlterModelOptions(
            name="q18ranking",
            options={
                "verbose_name": "Места по 18 показателю",
                "verbose_name_plural": "Места по 18 показателю",
            },
        ),
        migrations.AlterModelOptions(
            name="q18tandemranking",
            options={
                "verbose_name": "Тандем-места по 18 показателю",
                "verbose_name_plural": "Тандем-места по 18 показателю",
            },
        ),
        migrations.AlterField(
            model_name="q18detachmentreport",
            name="june_15_detachment_members",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="q18detachmentreport",
            name="score",
            field=models.FloatField(default=0, verbose_name="Очки"),
        ),
    ]
