# Generated by Django 4.2.7 on 2024-03-22 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0002_linksq7_linksq8_q10_q10ranking_q10report_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="q10",
            options={
                "verbose_name": "Q10 призовое место",
                "verbose_name_plural": "Q10 призовые места",
            },
        ),
        migrations.AlterModelOptions(
            name="q11",
            options={
                "verbose_name": "Q11 призовое место",
                "verbose_name_plural": "Q11 призовые места",
            },
        ),
        migrations.AlterModelOptions(
            name="q12",
            options={
                "verbose_name": "Q12 призовое место",
                "verbose_name_plural": "Q12 призовые места",
            },
        ),
        migrations.AlterModelOptions(
            name="q7",
            options={"verbose_name": "Q7 участия", "verbose_name_plural": "Q7 участия"},
        ),
        migrations.AlterModelOptions(
            name="q8",
            options={"verbose_name": "Q8 участие", "verbose_name_plural": "Q8 участия"},
        ),
        migrations.AlterModelOptions(
            name="q9",
            options={
                "verbose_name": "Q9 призовое место",
                "verbose_name_plural": "Q9 призовые места",
            },
        ),
        migrations.RemoveConstraint(
            model_name="q13detachmentreport",
            name="unique_report_q13detachmentreport",
        ),
        migrations.RemoveConstraint(
            model_name="q18detachmentreport",
            name="unique_report_q18detachmentreport",
        ),
    ]
