# Generated by Django 4.2.7 on 2024-02-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "competitions",
            "0002_score_prizeplacesindistrandinterreglaborprojects_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="prize_places_in_all_russian_events",
            field=models.FloatField(default=100.0, verbose_name="Среднее место"),
        ),
        migrations.AlterField(
            model_name="score",
            name="prize_places_in_all_russian_labor_projects",
            field=models.FloatField(default=100.0, verbose_name="Среднее место"),
        ),
        migrations.AlterField(
            model_name="score",
            name="prize_places_in_distr_and_interreg_events",
            field=models.FloatField(default=100.0, verbose_name="Среднее место"),
        ),
        migrations.AlterField(
            model_name="score",
            name="prize_places_in_distr_and_interreg_labor_projects",
            field=models.FloatField(default=100.0, verbose_name="Среднее место"),
        ),
    ]
