# Generated by Django 4.2.7 on 2024-03-10 16:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0029_alter_centralheadquarter_name_alter_detachment_name_and_more'),
        ('competitions', '0003_alter_score_prize_places_in_all_russian_events_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q13DetachmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q13_raws', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q13_raws', to='headquarters.detachment', verbose_name='Отряд')),
            ],
        ),
        migrations.CreateModel(
            name='Q13EventOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Спортивное', 'Спортивное'), ('Интеллектуальное', 'Интеллектуальное'), ('Творческое', 'Творческое'), ('Волонтерское', 'Волонтерское'), ('Внутреннее', 'Внутреннее')], default='Внутреннее', max_length=16, verbose_name='Тип мероприятия')),
                ('event_link', models.URLField(max_length=500, verbose_name='Ссылка на пуб.')),
            ],
        ),
        migrations.CreateModel(
            name='Q13ReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q13_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.q13eventorganization')),
                ('q13_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.q13detachmentreport')),
            ],
        ),
        migrations.CreateModel(
            name='Q13Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Итоговое место по показателю')),
                ('detachment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='q13_score', to='headquarters.detachment', verbose_name='Отряд')),
            ],
        ),
        migrations.AddField(
            model_name='q13detachmentreport',
            name='organization_data',
            field=models.ManyToManyField(blank=True, through='competitions.Q13ReportData', to='competitions.q13eventorganization', verbose_name='Проведенные мероприятия'),
        ),
    ]
