# Generated by Django 4.2.7 on 2024-02-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0003_linksofparticipationinallrussianevents_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="participation_in_all_russian_events",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Оценка"),
        ),
    ]
