# Generated by Django 4.2.7 on 2024-03-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_alter_q10_options_alter_q11_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q13tandemranking',
            name='place',
            field=models.FloatField(default=6.0, verbose_name='Итоговое место по показателю'),
        ),
        migrations.AlterField(
            model_name='q18detachmentreport',
            name='score',
            field=models.FloatField(default=1000, verbose_name='Очки'),
        ),
        migrations.AddConstraint(
            model_name='q13detachmentreport',
            constraint=models.UniqueConstraint(fields=('competition', 'detachment'), name='unique_report_q13detachmentreport'),
        ),
        migrations.AddConstraint(
            model_name='q18detachmentreport',
            constraint=models.UniqueConstraint(fields=('competition', 'detachment'), name='unique_report_q18detachmentreport'),
        ),
    ]
