# Generated by Django 4.2.7 on 2024-03-17 06:50

import competitions.models
import competitions.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "headquarters",
            "0029_alter_centralheadquarter_name_alter_detachment_name_and_more",
        ),
        ("competitions", "0004_alter_q7ranking_place_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Q8TandemRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.PositiveSmallIntegerField(
                        verbose_name="Итоговое место по показателю 8"
                    ),
                ),
                (
                    "detachment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_main_detachment",
                        to="headquarters.detachment",
                        verbose_name="Отряд-наставник",
                    ),
                ),
                (
                    "junior_detachment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_junior_detachment",
                        to="headquarters.detachment",
                        verbose_name="Младший отряд",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Q8Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Общее количество участий"
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_competition_reports",
                        to="competitions.competitions",
                    ),
                ),
                (
                    "detachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_detachment_reports",
                        to="headquarters.detachment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(competitions.models.CalcBase, models.Model),
        ),
        migrations.CreateModel(
            name="Q8Ranking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.PositiveSmallIntegerField(
                        verbose_name="Итоговое место по показателю 8"
                    ),
                ),
                (
                    "detachment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.detachment",
                        verbose_name="Отряд",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Q8",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        max_length=255, verbose_name="Название мероприятия"
                    ),
                ),
                (
                    "certificate_scans",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=competitions.utils.get_certificate_scans_path,
                        verbose_name="Сканы сертификатов",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания заявки"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Подтверждено"),
                ),
                (
                    "number_of_participants",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Количество участников",
                    ),
                ),
                (
                    "detachment_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participation_data",
                        to="competitions.q8report",
                        verbose_name="Отчет отряда",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участие во всероссийских мероприятиях",
                "verbose_name_plural": "Участия во всероссийских мероприятиях",
            },
        ),
        migrations.CreateModel(
            name="LinksQ8",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField(max_length=500, verbose_name="Ссылка")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="competitions.q8",
                        verbose_name="Участие во всероссийских мероприятиях",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка на фотоотчет участия СО во всероссийском мероприятии",
                "verbose_name_plural": "Ссылки на фотоотчет участия СО во всероссийских мероприятиях",
            },
        ),
        migrations.AddConstraint(
            model_name="q8",
            constraint=models.UniqueConstraint(
                fields=("detachment_report", "event_name"),
                name="unique_participation_in_all_russian_events",
            ),
        ),
        migrations.AddConstraint(
            model_name="linksq8",
            constraint=models.UniqueConstraint(
                fields=("event", "link"), name="unique_event_link_all_russian_events"
            ),
        ),
    ]
