# Generated by Django 4.2.7 on 2024-03-24 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "competitions",
            "0005_alter_q19ranking_options_q20tandemranking_q20report_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="linksq7",
            name="link",
            field=models.URLField(max_length=300, verbose_name="Ссылка"),
        ),
        migrations.AlterField(
            model_name="linksq8",
            name="link",
            field=models.URLField(max_length=300, verbose_name="Ссылка"),
        ),
        migrations.AlterField(
            model_name="q10",
            name="event_name",
            field=models.CharField(max_length=150, verbose_name="Название мероприятия"),
        ),
        migrations.AlterField(
            model_name="q11",
            name="event_name",
            field=models.CharField(max_length=150, verbose_name="Название мероприятия"),
        ),
        migrations.AlterField(
            model_name="q12",
            name="event_name",
            field=models.CharField(max_length=150, verbose_name="Название мероприятия"),
        ),
        migrations.AlterField(
            model_name="q20report",
            name="link_banner",
            field=models.URLField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="Ссылка на фото знамени",
            ),
        ),
        migrations.AlterField(
            model_name="q20report",
            name="link_banner_img",
            field=models.URLField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="Ссылка на изображение знамени",
            ),
        ),
        migrations.AlterField(
            model_name="q20report",
            name="link_emblem",
            field=models.URLField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="Ссылка на фото эмблемы",
            ),
        ),
        migrations.AlterField(
            model_name="q20report",
            name="link_emblem_img",
            field=models.URLField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="Ссылка на изображение эмблемы",
            ),
        ),
        migrations.AlterField(
            model_name="q20report",
            name="link_flag",
            field=models.URLField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="Ссылка на фото флага",
            ),
        ),
        migrations.AlterField(
            model_name="q20report",
            name="link_flag_img",
            field=models.URLField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="Ссылка на изображение флага",
            ),
        ),
        migrations.AlterField(
            model_name="q7",
            name="event_name",
            field=models.CharField(max_length=150, verbose_name="Название мероприятия"),
        ),
        migrations.AlterField(
            model_name="q7",
            name="number_of_participants",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name="Количество участников",
            ),
        ),
        migrations.AlterField(
            model_name="q8",
            name="event_name",
            field=models.CharField(max_length=150, verbose_name="Название мероприятия"),
        ),
        migrations.AlterField(
            model_name="q8",
            name="number_of_participants",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
                verbose_name="Количество участников",
            ),
        ),
        migrations.AlterField(
            model_name="q9",
            name="event_name",
            field=models.CharField(max_length=150, verbose_name="Название мероприятия"),
        ),
    ]
