# Generated by Django 4.2.7 on 2024-03-18 17:08

import competitions.models
import competitions.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "headquarters",
            "0029_alter_centralheadquarter_name_alter_detachment_name_and_more",
        ),
        ("competitions", "0005_q8tandemranking_q8report_q8ranking_q8_linksq8_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Q9TandemRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.PositiveSmallIntegerField(
                        verbose_name="Итоговое место по показателю 8"
                    ),
                ),
                (
                    "detachment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_main_detachment",
                        to="headquarters.detachment",
                        verbose_name="Отряд-наставник",
                    ),
                ),
                (
                    "junior_detachment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_junior_detachment",
                        to="headquarters.detachment",
                        verbose_name="Младший отряд",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Q9Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Общее количество участий"
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_competition_reports",
                        to="competitions.competitions",
                    ),
                ),
                (
                    "detachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_detachment_reports",
                        to="headquarters.detachment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(competitions.models.CalcBase, models.Model),
        ),
        migrations.CreateModel(
            name="Q9Ranking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.PositiveSmallIntegerField(
                        verbose_name="Итоговое место по показателю 8"
                    ),
                ),
                (
                    "detachment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.detachment",
                        verbose_name="Отряд",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Q9",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        max_length=255, verbose_name="Название мероприятия"
                    ),
                ),
                (
                    "certificate_scans",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=competitions.utils.get_certificate_scans_path,
                        verbose_name="Сканы сертификатов",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания заявки"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Подтверждено"),
                ),
                (
                    "prize_place",
                    models.IntegerField(
                        choices=[
                            (1, "Первое место"),
                            (2, "Второе место"),
                            (3, "Третье место"),
                        ],
                        verbose_name="Призовое место",
                    ),
                ),
                (
                    "detachment_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participation_data",
                        to="competitions.q9report",
                        verbose_name="Отчет отряда",
                    ),
                ),
            ],
            options={
                "verbose_name": "Призовое место в окружных и межрегиональных мероприятиях и конкурсах РСО",
                "verbose_name_plural": "Призовые места в окружных и межрегиональных мероприятиях и конкурсах РСО",
            },
        ),
        migrations.AddConstraint(
            model_name="q9",
            constraint=models.UniqueConstraint(
                fields=("detachment_report", "event_name"),
                name="unique_prize_places_in_distr_and_interreg_events",
            ),
        ),
    ]
