# Generated by Django 4.2.7 on 2024-02-19 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "headquarters",
            "0029_alter_centralheadquarter_name_alter_detachment_name_and_more",
        ),
        ("competitions", "0005_prizeplacesindistrandinterregevents_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participationinallrussianevents",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="competitions.competitions",
                verbose_name="Конкурс",
            ),
        ),
        migrations.AlterField(
            model_name="participationinallrussianevents",
            name="detachment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="headquarters.detachment",
                verbose_name="Отряд",
            ),
        ),
        migrations.AlterField(
            model_name="participationindistrandinterregevents",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="competitions.competitions",
                verbose_name="Конкурс",
            ),
        ),
        migrations.AlterField(
            model_name="participationindistrandinterregevents",
            name="detachment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="headquarters.detachment",
                verbose_name="Отряд",
            ),
        ),
        migrations.AlterField(
            model_name="prizeplacesindistrandinterregevents",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="competitions.competitions",
                verbose_name="Конкурс",
            ),
        ),
        migrations.AlterField(
            model_name="prizeplacesindistrandinterregevents",
            name="detachment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="headquarters.detachment",
                verbose_name="Отряд",
            ),
        ),
    ]
