# Generated by Django 4.2.7 on 2024-03-16 19:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0029_alter_centralheadquarter_name_alter_detachment_name_and_more'),
        ('competitions', '0006_q13ranking_q13tandemranking_q18detachmentreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q2DetachmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_competition_reports', to='competitions.competitions')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_detachment_reports', to='competitions.competitions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Q2TandemRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveSmallIntegerField(verbose_name='Итоговое место по показателю')),
                ('detachment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_main_detachment', to='headquarters.detachment', verbose_name='Отряд-наставник')),
                ('junior_detachment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_junior_detachment', to='headquarters.detachment', verbose_name='Младший отряд')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Q2Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Итоговое место по показателю')),
                ('detachment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.detachment', verbose_name='Отряд')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Q2Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commander_achievment', models.BooleanField(default=False, verbose_name='Региональная школа командного состава пройдена командиром отряда')),
                ('commissioner_achievment', models.BooleanField(default=False, verbose_name='Региональная школа командного состава пройдена комиссаром отряда')),
                ('commander_link', models.URLField(verbose_name='Ссылка на публикацию о прохождении школы командного состава командиром отряда')),
                ('commissioner_link', models.URLField(verbose_name='Ссылка на публикацию о прохождении школы командного состава комиссаром отряда')),
                ('detachment_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='competitions.q2detachmentreport', verbose_name='Отчет-2 отряда')),
            ],
        ),
    ]
