# Generated by Django 4.2.7 on 2024-02-21 05:05

import competitions.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "headquarters",
            "0029_alter_centralheadquarter_name_alter_detachment_name_and_more",
        ),
        (
            "competitions",
            "0006_alter_participationinallrussianevents_competition_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prizeplacesindistrandinterregevents",
            options={
                "ordering": ["-competition__id"],
                "verbose_name": "Призовое место в окружных и межрегиональных мероприятиях и конкурсах РСО",
                "verbose_name_plural": "Призовые места в окружных и межрегиональных мероприятиях и конкурсах РСО",
            },
        ),
        migrations.AlterField(
            model_name="score",
            name="participation_in_all_russian_events",
            field=models.PositiveSmallIntegerField(
                default=100, verbose_name="Среднее место"
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="participation_in_distr_and_interreg_events",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Общее количество участий"
            ),
        ),
        migrations.CreateModel(
            name="PrizePlacesInAllRussianEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        max_length=255, verbose_name="Название мероприятия"
                    ),
                ),
                (
                    "certificate_scans",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=competitions.utils.get_certificate_scans_path,
                        verbose_name="Сканы сертификатов",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания заявки"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Подтверждено"),
                ),
                (
                    "prize_place",
                    models.IntegerField(
                        choices=[
                            (1, "Первое место"),
                            (2, "Второе место"),
                            (3, "Третье место"),
                        ],
                        verbose_name="Призовое место",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="competitions.competitions",
                        verbose_name="Конкурс",
                    ),
                ),
                (
                    "detachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.detachment",
                        verbose_name="Отряд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Призовое место во всероссийских мероприятиях и конкурсах РСО",
                "verbose_name_plural": "Призовые места во всероссийских мероприятиях и конкурсах РСО",
                "ordering": ["-competition__id"],
            },
        ),
        migrations.AddConstraint(
            model_name="prizeplacesinallrussianevents",
            constraint=models.UniqueConstraint(
                fields=("competition", "detachment", "event_name"),
                name="unique_prize_places_in_all_russian_events",
            ),
        ),
    ]
