# Generated by Django 4.2.7 on 2024-03-24 05:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0029_alter_centralheadquarter_name_alter_detachment_name_and_more'),
        ('competitions', '0006_alter_linksq7_link_alter_linksq8_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q2TandemRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.FloatField(default=3.0, verbose_name='Итоговое место по показателю в тандеме')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_main_detachment', to='headquarters.detachment', verbose_name='Отряд-наставник')),
                ('junior_detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_junior_detachment', to='headquarters.detachment', verbose_name='Младший отряд')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Q2Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Итоговое место по показателю')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.detachment', verbose_name='Отряд')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Q2DetachmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('commander_achievement', models.BooleanField(default=False, verbose_name='Региональная школа командного состава пройдена командиром отряда')),
                ('commissioner_achievement', models.BooleanField(default=False, verbose_name='Региональная школа командного состава пройдена комиссаром отряда')),
                ('commander_link', models.URLField(verbose_name='Ссылка на публикацию о прохождении школы командного состава командиром отряда')),
                ('commissioner_link', models.URLField(verbose_name='Ссылка на публикацию о прохождении школы командного состава комиссаром отряда')),
                ('individual_place', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Расчетное место по показателю')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_competition_reports', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_detachment_reports', to='headquarters.detachment', verbose_name='Отряд')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='q2tandemranking',
            constraint=models.UniqueConstraint(fields=('competition', 'detachment', 'junior_detachment'), name='unique_tandem_ranking_q2tandemranking'),
        ),
        migrations.AddConstraint(
            model_name='q2tandemranking',
            constraint=models.UniqueConstraint(fields=('competition', 'detachment'), name='unique_main_ranking_q2tandemranking'),
        ),
        migrations.AddConstraint(
            model_name='q2tandemranking',
            constraint=models.UniqueConstraint(fields=('competition', 'junior_detachment'), name='unique_junior_ranking_q2tandemranking'),
        ),
        migrations.AddConstraint(
            model_name='q2ranking',
            constraint=models.UniqueConstraint(fields=('competition', 'detachment'), name='unique_ranking_q2ranking'),
        ),
        migrations.AddConstraint(
            model_name='q2detachmentreport',
            constraint=models.UniqueConstraint(fields=('competition', 'detachment'), name='unique_report_q2detachmentreport'),
        ),
    ]
