# Generated by Django 4.2.7 on 2024-03-16 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0029_alter_centralheadquarter_name_alter_detachment_name_and_more'),
        ('competitions', '0006_q13ranking_q13tandemranking_q18detachmentreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q13detachmentreport',
            name='detachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_detachment_reports', to='headquarters.detachment'),
        ),
        migrations.AlterField(
            model_name='q18detachmentreport',
            name='detachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_detachment_reports', to='headquarters.detachment'),
        ),
    ]
