# Generated by Django 4.2.7 on 2024-03-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_q2detachmentreport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='q2detachmentreport',
            name='q2_links',
        ),
    ]
