# Generated by Django 4.2.7 on 2024-03-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "competitions",
            "0007_q10ranking_competition_q10tandemranking_competition_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="q10report",
            name="score",
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name="Среднее призовое место"
            ),
        ),
        migrations.AlterField(
            model_name="q11report",
            name="score",
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name="Среднее призовых мест"
            ),
        ),
        migrations.AlterField(
            model_name="q12report",
            name="score",
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name="Среднее призовых мест"
            ),
        ),
        migrations.AlterField(
            model_name="q9report",
            name="score",
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name="Среднее призовое место"
            ),
        ),
    ]
