# Generated by Django 4.2.7 on 2024-03-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_alter_q13detachmentreport_detachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q13tandemranking',
            name='place',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='Итоговое место по показателю'),
        ),
    ]
