# Generated by Django 4.2.7 on 2024-03-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_q2tandemranking_q2ranking_q2detachmentreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q2detachmentreport',
            name='commander_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на публикацию о прохождении школы командного состава командиром отряда'),
        ),
        migrations.AlterField(
            model_name='q2detachmentreport',
            name='commissioner_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на публикацию о прохождении школы командного состава комиссаром отряда'),
        ),
    ]
