# Generated by Django 4.2.7 on 2024-02-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "competitions",
            "0007_alter_prizeplacesindistrandinterregevents_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="prize_places_in_all_russian_events",
            field=models.PositiveSmallIntegerField(
                default=100, verbose_name="Среднее место"
            ),
        ),
        migrations.AddField(
            model_name="score",
            name="prize_places_in_distr_and_interreg_events",
            field=models.PositiveSmallIntegerField(
                default=100, verbose_name="Среднее место"
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="participation_in_all_russian_events",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Общее количество участий"
            ),
        ),
    ]
