# Generated by Django 4.2.7 on 2024-03-16 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0029_alter_centralheadquarter_name_alter_detachment_name_and_more'),
        ('competitions', '0008_alter_q13tandemranking_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q13tandemranking',
            name='detachment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_main_detachment', to='headquarters.detachment', verbose_name='Отряд-наставник'),
        ),
        migrations.AlterField(
            model_name='q13tandemranking',
            name='junior_detachment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_junior_detachment', to='headquarters.detachment', verbose_name='Младший отряд'),
        ),
        migrations.AlterField(
            model_name='q18tandemranking',
            name='detachment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_main_detachment', to='headquarters.detachment', verbose_name='Отряд-наставник'),
        ),
        migrations.AlterField(
            model_name='q18tandemranking',
            name='junior_detachment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_junior_detachment', to='headquarters.detachment', verbose_name='Младший отряд'),
        ),
    ]
