# Generated by Django 4.2.7 on 2024-03-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_alter_q2detachmentreport_commander_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q18ranking',
            name='place',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Итоговое место по показателю'),
        ),
        migrations.AlterField(
            model_name='q18tandemranking',
            name='place',
            field=models.FloatField(default=2.0, verbose_name='Итоговое место по показателю'),
        ),
    ]
