# Generated by Django 4.2.7 on 2024-03-21 01:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0008_alter_q10report_score_alter_q11report_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="q10report",
            name="score",
            field=models.FloatField(
                default=4,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="Среднее призовое место",
            ),
        ),
        migrations.AlterField(
            model_name="q11report",
            name="score",
            field=models.FloatField(
                default=4,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="Среднее призовое место",
            ),
        ),
        migrations.AlterField(
            model_name="q12report",
            name="score",
            field=models.FloatField(
                default=4,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="Среднее призовое место",
            ),
        ),
        migrations.AlterField(
            model_name="q9report",
            name="score",
            field=models.FloatField(
                default=4,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="Среднее призовое место",
            ),
        ),
    ]
