# Generated by Django 4.2.7 on 2024-03-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_remove_q2detachmentreport_q2_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='q2detachmentreport',
            name='commander_achievement',
            field=models.BooleanField(default=False, verbose_name='Региональная школа командного состава пройдена командиром отряда'),
        ),
        migrations.AddField(
            model_name='q2detachmentreport',
            name='commander_link',
            field=models.URLField(default='https://music.yandex.ru/home', verbose_name='Ссылка на публикацию о прохождении школы командного состава командиром отряда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='q2detachmentreport',
            name='commissioner_achievement',
            field=models.BooleanField(default=False, verbose_name='Региональная школа командного состава пройдена комиссаром отряда'),
        ),
        migrations.AddField(
            model_name='q2detachmentreport',
            name='commissioner_link',
            field=models.URLField(default='https://music.yandex.ru/home', verbose_name='Ссылка на публикацию о прохождении школы командного состава комиссаром отряда'),
            preserve_default=False,
        ),
    ]
