# Generated by Django 4.2.7 on 2024-03-21 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "headquarters",
            "0029_alter_centralheadquarter_name_alter_detachment_name_and_more",
        ),
        ("competitions", "0009_alter_q10report_score_alter_q11report_score_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="q10ranking",
            options={
                "verbose_name": "Место по 10 показателю",
                "verbose_name_plural": "Места по 10 показателю",
            },
        ),
        migrations.AlterModelOptions(
            name="q10tandemranking",
            options={
                "verbose_name": "Тандем-место по 10 показателю",
                "verbose_name_plural": "Тандем-места по 10 показателю",
            },
        ),
        migrations.AlterModelOptions(
            name="q11ranking",
            options={
                "verbose_name": "Место по 11 показателю",
                "verbose_name_plural": "Места по 11 показателю",
            },
        ),
        migrations.AlterModelOptions(
            name="q11tandemranking",
            options={
                "verbose_name": "Тандем-место по 11 показателю",
                "verbose_name_plural": "Тандем-места по 11 показателю",
            },
        ),
        migrations.AlterModelOptions(
            name="q12ranking",
            options={
                "verbose_name": "Место по 12 показателю",
                "verbose_name_plural": "Места по 12 показателю",
            },
        ),
        migrations.AlterModelOptions(
            name="q12tandemranking",
            options={
                "verbose_name": "Тандем-место по 12 показателю",
                "verbose_name_plural": "Тандем-места по 12 показателю",
            },
        ),
        migrations.AlterModelOptions(
            name="q7ranking",
            options={
                "verbose_name": "Место по 7 показателю",
                "verbose_name_plural": "Места по 7 показателю",
            },
        ),
        migrations.AlterModelOptions(
            name="q7tandemranking",
            options={
                "verbose_name": "Тандем-место по 7 показателю",
                "verbose_name_plural": "Тандем-места по 7 показателю",
            },
        ),
        migrations.AlterModelOptions(
            name="q8ranking",
            options={
                "verbose_name": "Место по 8 показателю",
                "verbose_name_plural": "Места по 8 показателю",
            },
        ),
        migrations.AlterModelOptions(
            name="q8tandemranking",
            options={
                "verbose_name": "Тандем-место по 8 показателю",
                "verbose_name_plural": "Тандем-места по 8 показателю",
            },
        ),
        migrations.AlterModelOptions(
            name="q9ranking",
            options={
                "verbose_name": "Место по 9 показателю",
                "verbose_name_plural": "Места по 9 показателю",
            },
        ),
        migrations.AlterModelOptions(
            name="q9tandemranking",
            options={
                "verbose_name": "Тандем-место по 9 показателю",
                "verbose_name_plural": "Тандем-места по 9 показателю",
            },
        ),
        migrations.CreateModel(
            name="Q1TandemRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.PositiveSmallIntegerField(
                        verbose_name="Итоговое место по показателю 1"
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="competitions.competitions",
                        verbose_name="Конкурс",
                    ),
                ),
                (
                    "detachment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_main_detachment",
                        to="headquarters.detachment",
                        verbose_name="Отряд-наставник",
                    ),
                ),
                (
                    "junior_detachment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_junior_detachment",
                        to="headquarters.detachment",
                        verbose_name="Младший отряд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тандем-место по 1 показателю",
                "verbose_name_plural": "Тандем-места по 1 показателю",
            },
        ),
        migrations.CreateModel(
            name="Q1Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Общее количество участий"
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_competition_reports",
                        to="competitions.competitions",
                    ),
                ),
                (
                    "detachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_detachment_reports",
                        to="headquarters.detachment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Q1Ranking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.PositiveSmallIntegerField(
                        verbose_name="Итоговое место по показателю 1"
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="competitions.competitions",
                        verbose_name="Конкурс",
                    ),
                ),
                (
                    "detachment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="headquarters.detachment",
                        verbose_name="Отряд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Место по 1 показателю",
                "verbose_name_plural": "Места по 1 показателю",
            },
        ),
    ]
