# Generated by Django 4.2.7 on 2024-03-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_alter_q18ranking_place_alter_q18tandemranking_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q18ranking',
            name='place',
            field=models.PositiveSmallIntegerField(verbose_name='Итоговое место по показателю'),
        ),
        migrations.AlterField(
            model_name='q18tandemranking',
            name='place',
            field=models.PositiveSmallIntegerField(verbose_name='Итоговое место по показателю'),
        ),
    ]
