# Generated by Django 4.2.7 on 2024-03-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_q2detachmentreport_commander_achievement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='q2detachmentreport',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='q2tandemranking',
            name='place',
            field=models.PositiveSmallIntegerField(verbose_name='Итоговое место по показателю в тандеме'),
        ),
        migrations.DeleteModel(
            name='Q2Links',
        ),
    ]
