# Generated by Django 4.2.7 on 2024-03-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_alter_q13tandemranking_detachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q18detachmentreport',
            name='score',
            field=models.FloatField(default=0, verbose_name='Очки'),
        ),
    ]
