# Generated by Django 4.2.7 on 2024-03-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_alter_q18ranking_place_alter_q18tandemranking_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q19ranking',
            name='place',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Итоговое место по показателю 19'),
        ),
        migrations.AlterField(
            model_name='q19tandemranking',
            name='place',
            field=models.FloatField(default=2.0, verbose_name='Итоговое место по показателю 19'),
        ),
    ]
