# Generated by Django 4.2.7 on 2024-03-19 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_q2detachmentreport_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='q2detachmentreport',
            name='individual_place',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Расчетное место по показателю'),
        ),
    ]
