# Generated by Django 4.2.7 on 2024-03-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_alter_q2ranking_options_and_more'),
        ('competitions', '0011_alter_q19ranking_place_alter_q19tandemranking_place'),
    ]

    operations = [
    ]
