# Generated by Django 4.2.7 on 2024-03-24 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_merge_20240324_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='q2detachmentreport',
            options={'verbose_name': 'Отчет по 2 показателю', 'verbose_name_plural': 'Отчеты по 2 показателю'},
        ),
        migrations.RemoveConstraint(
            model_name='q2detachmentreport',
            name='unique_report_q2detachmentreport',
        ),
        migrations.AlterField(
            model_name='q19ranking',
            name='place',
            field=models.PositiveSmallIntegerField(verbose_name='Итоговое место по показателю 19'),
        ),
        migrations.AlterField(
            model_name='q19tandemranking',
            name='place',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Итоговое место по показателю 19'),
        ),
    ]
