# Generated by Django 4.2.7 on 2024-03-25 08:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0029_alter_centralheadquarter_name_alter_detachment_name_and_more'),
        ('competitions', '0014_q4tandemranking_q4ranking_q3tandemranking_q3ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q5DetachmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('june_15_detachment_members', models.PositiveSmallIntegerField(default=1)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_competition_reports', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_detachment_reports', to='headquarters.detachment', verbose_name='Отряд')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='q3ranking',
            options={'verbose_name': 'Место по 3 показателю', 'verbose_name_plural': 'Места по 3 показателю'},
        ),
        migrations.AlterModelOptions(
            name='q3tandemranking',
            options={'verbose_name': 'Тандем-место по 3 показателю', 'verbose_name_plural': 'Тандем-места по 3 показателю'},
        ),
        migrations.AlterModelOptions(
            name='q4ranking',
            options={'verbose_name': 'Место по 4 показателю', 'verbose_name_plural': 'Места по 4 показателю'},
        ),
        migrations.AlterModelOptions(
            name='q4tandemranking',
            options={'verbose_name': 'Тандем-место по 4 показателю', 'verbose_name_plural': 'Тандем-места по 4 показателю'},
        ),
        migrations.CreateModel(
            name='Q5TandemRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.FloatField(default=20.0, verbose_name='Итоговое место по показателю')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_main_detachment', to='headquarters.detachment', verbose_name='Отряд-наставник')),
                ('junior_detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_junior_detachment', to='headquarters.detachment', verbose_name='Младший отряд')),
            ],
            options={
                'verbose_name': 'Тандем-места по 13 показателю',
                'verbose_name_plural': 'Тандем-места по 13 показателю',
            },
        ),
        migrations.CreateModel(
            name='Q5Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Итоговое место по показателю')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='headquarters.detachment', verbose_name='Отряд')),
            ],
            options={
                'verbose_name': 'Места по 13 показателю',
                'verbose_name_plural': 'Места по 13 показателю',
            },
        ),
        migrations.CreateModel(
            name='Q5EducatedParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО участника, прошедшего профессиональное обучение')),
                ('document', models.FileField(upload_to='', verbose_name='Документ, подтверждающий прохождение профессионального обучения.')),
                ('is_verified', models.BooleanField(default=False)),
                ('detachment_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.q5detachmentreport', verbose_name='Отчет')),
            ],
        ),
        migrations.AddConstraint(
            model_name='q5detachmentreport',
            constraint=models.UniqueConstraint(fields=('competition', 'detachment'), name='unique_report_q5detachmentreport'),
        ),
    ]
