# Generated by Django 4.2.7 on 2024-03-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_q15event_q15link_q5detachmentreport_and_more'),
        ('competitions', '0015_q5detachmentreport_alter_q3ranking_options_and_more'),
    ]

    operations = [
    ]
