# Generated by Django 4.2.7 on 2024-03-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0016_merge_20240326_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='q5detachmentreport',
            name='june_15_detachment_members',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
