# Generated by Django 4.2.7 on 2024-03-26 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0029_alter_centralheadquarter_name_alter_detachment_name_and_more'),
        ('competitions', '0017_q5detachmentreport_june_15_detachment_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q17DetachmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_competition_reports', to='competitions.competitions', verbose_name='Конкурс')),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_detachment_reports', to='headquarters.detachment', verbose_name='Отряд')),
            ],
            options={
                'verbose_name': 'Отчет по 17 показателю',
                'verbose_name_plural': 'Отчеты по 17 показателю',
            },
        ),
        migrations.RenameModel(
            old_name='Q15Ranking',
            new_name='Q17Ranking',
        ),
        migrations.RenameModel(
            old_name='Q15TandemRanking',
            new_name='Q17TandemRanking',
        ),
        migrations.AlterModelOptions(
            name='q17ranking',
            options={'verbose_name': 'Место по 17 показателю', 'verbose_name_plural': 'Места по 17 показателю'},
        ),
        migrations.AlterModelOptions(
            name='q17tandemranking',
            options={'verbose_name': 'Тандем-место по 17 показателю', 'verbose_name_plural': 'Тандем-места по 17 показателю'},
        ),
        migrations.RenameModel(
            old_name='Q15Event',
            new_name='Q17Event',
        ),
        migrations.RenameModel(
            old_name='Q15Link',
            new_name='Q17Link',
        ),
        migrations.DeleteModel(
            name='Q15DetachmentReport',
        ),
        migrations.AddField(
            model_name='q17detachmentreport',
            name='q17_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q17_event', to='competitions.q17event', verbose_name='Название источника статьи'),
        ),
        migrations.AddField(
            model_name='q17detachmentreport',
            name='q17_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q17_link', to='competitions.q17link', verbose_name='Ссылка на статью об участии отряда'),
        ),
    ]
