# Generated by Django 4.2.7 on 2024-03-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_q17detachmentreport_rename_q15ranking_q17ranking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q5educatedparticipant',
            name='document',
            field=models.FileField(blank=True, upload_to='', verbose_name='Документ, подтверждающий прохождение профессионального обучения.'),
        ),
    ]
